### ISSUE TITLE
Strange behavior with markup option

### ISSUE THREAD

**Issue by jondeandres** [signavio/react-mentions#19]
Hi,

I'm having an strange behavior with the next configuration:

``` jsx
<MentionsInput
          value={this.state.textAreaValue}
          onChange={this.handleTextAreaChange}
          markup="@__display__"
          displayTransform={this.mentionDisplayTransform}>

            <Mention
              type="user"
              trigger="@"
              renderSuggestion={this.renderSuggestion}
              data={mentionNames}
             />
          </MentionsInput>

// functions
handleTextAreaChange: function(ev, newValue) {
    this.setState({textAreaValue: newValue});
  },

  renderSuggestion: function(id, display, search, highlightedDisplay) {
    return (
      <div className="suggestion-item">
        @{highlightedDisplay}
      </div>
    );
  },

  mentionDisplayTransform: function(id, display, type) {
    return "@" + display;
  }
```

The caret is sometimes blocked, and you can't type anymore after add a mention. If I remove the `markup` property it works fine, but that's breaking some stuff in our backend.

Could you take a look at this?

Thanks and congrats for this library, despite this and https://github.com/effektif/react-mentions/pull/18 it works pretty well.

**Comment by jfschwarz** [comment]
The caret being blocked seems weird indeed. Anyways, your markup format will be problematic with current react-mention implementation. From the markup value `@__display__` react-mentions will derive a regexp looking like this: `@(.+?)`. This will match the shortest sequence of an "@" followed by any character. E.g., aplied on the string "hi @johndoe", instead of matching "@johndoe", it will only match "@j".

Have a look at the function `markupToRegex` in `utils.jsx` for a better understanding. You might want to customize the implementation of that function. Potentially, we might add a prop for passing in a regexp in addition to the markup.

**Comment by jondeandres** [comment]
@jfschwarz any idea of which regex we should use? Or some other details about this?

Thanks

**Comment by jfschwarz** [comment]
Check out branch "custom-regex". I just added support for passing in a prop "regexp" to the `MentionsInput` component. You would probably want to use a regex like this:

```
/(?:^|\s)@(\w+)(?:$|\s)/g
```

(The first, non-capturing groups makes sure the pattern is either at the start of the string or starting with a whitespace char. The second, capturing group extracts the ID for the mention. The third, non-capturing group matches the end of the string or whitespace.)

Hope this helps.

**Comment by jondeandres** [comment]
Hi again @jfschwarz,

after the issue with the `lib/index.js`, now seems I have a problem trying your `custom-regex` branch. Seems that the call to `autogrowTextarea` in `MentionsInput.componentDidMount` is failing. The stack trace:

```
ReactMount.findComponentRoot ReactMount.js:606
ReactMount.findReactNodeByID ReactMount.js:552
getNode ReactMount.js:128
ReactBrowserComponentMixin.getDOMNode ReactBrowserComponentMixin.js:35
module.exports.React.createClass.autogrowTextarea MentionsInput.js:367
module.exports.React.createClass.componentDidMount MentionsInput.js:396
```

**Comment by jondeandres** [comment]
BTW, we are using react and react-tools `0.12.x`.

**Comment by leviwheatcroft** [comment]
Just ran into this myself.. the fn @jfschwarz mentioned is [here](https://github.com/effektif/react-mentions/blob/master/src/utils.js#L46).

A hacky workaround is to put a character after the placeholder, in my own case I'm rendering with markdown so while `@__display__` doesn't work, `@*__display__*` works fine.

**Comment by kashifshamaz21** [comment]
@frontendphil @jfschwarz I'm trying to triage all the open issues on this library to see which ones are still relevant and that I can help out with. This one seems likely to have been fixed by the custom Regex PR long ago. If yes, then maybe one of you can close this bug? 
Thanks.

**Comment by hungnm11** [comment]
Hi, 

Anyone has an "Uncaught TypeError: Cannot read properties of undefined (reading 'markup')" issue on staging or production when clicked on list items for selected name ?

<img width="489" alt="image" src="https://github.com/signavio/react-mentions/assets/12028961/7fd845a3-6462-4707-9d77-f855d756a598">

**Comment by petrikkachur** [comment]
> Hi,
> 
> Anyone has met an "Uncaught TypeError: Cannot read properties of undefined (reading 'markup')" issue on staging or production when clicked on list items for selected name ?
> 
> On Local is worked well, this issue is only happened on Staging or production, I can not debug this issue on Staging or Production.
> 
> Running react-mentions => v4.4.10 with NextJS v"12.3.1"
> 
> the markup has defined `markup={'@[__display__](__id__)'}`
> 
> <img alt="image" width="489" src="https://private-user-images.githubusercontent.com/12028961/275703887-7fd845a3-6462-4707-9d77-f855d756a598.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzNzQ0MjUsIm5iZiI6MTcwODM3NDEyNSwicGF0aCI6Ii8xMjAyODk2MS8yNzU3MDM4ODctN2ZkODQ1YTMtNjQ2Mi00NzA3LTlkNzctZjg1NWQ3NTZhNTk4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE5VDIwMjIwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwZDU1ZDQ1OWE5ZGM4YTE1ODMxYTI0MTNmYTI5MTUxYTllMGUwODg5ODIyNjYxNWZkNjc3NTBjMzJmMzFlMjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WxGrE3NpOFYuQb_R3eBiHpF7-E7u0X-0hcGR2jhik64">

Have the same issue....

**Comment by sosegon** [comment]
For anyone facing this issue, the bug happens because Nextjs introduced a new compiler based on [SWC](http://swc.rs/) in [v12](https://nextjs.org/blog/next-12).

Unfortunately, that compiler optimizes [this code](https://github.com/signavio/react-mentions/blob/master/src/utils/iterateMentionsMarkup.js#L18) incorrectly. 

It goes from:

```
const captureGroupOffsets = config.map(({ markup }) => {
    const result = accOffset
    // + 1 is for the capturing group we add around each regexp component in combineRegExps
    accOffset += countPlaceholders(markup) + 1
    return result
  })
```

to:

```
l = t.map(function(e) {
    var t;
    return a += O(e.markup) + 1
})
```

So, it is evident that causes the error. The code should be like the following:

```
l = t.map(function(e) {
    var t = a;
    a += O(e.markup) + 1;
    return t;
})
```

So, a workaround to avoid this bug is to disable minification. In your next.config.js file, you should have something like this

```
module.exports = {
  swcMinify: false,
};
```

**Comment by hungnm11** [comment]
From @petrikkachur, he have fixed this issue 

Only need to change in src/utils/iterateMentionsMarkup.js:

 ```
const captureGroupOffsets = config.map(({ markup }) => {
 // + 1 is for the capturing group we add around each regexp component in combineRegExps let result
 if (markup !== undefined) {
 result = accOffset
 accOffset += countPlaceholders(markup) + 1
 return result
 }
 return result
 })
```

He has also fixed 
[https://www.npmjs.com/package/@peter_kachur_/react-mentions](https://www.npmjs.com/package/@peter_kachur_/react-mentions).

I have no chance for implementing this on porject again. so I share this, hope to help you.
Thank you  @petrikkachur for supported on this.
