### ISSUE TITLE
Mention Highlight does not scroll in Text Input

### ISSUE THREAD

**Issue by kkotelczuk** [signavio/react-mentions#210]
Hi,
I got text input with `max-height` and `overflow: scroll` on it. After mention reaches top edge of input it's highlight stays at position like on picture below
<img width="413" alt="screen shot 2017-12-11 at 16 37 02" src="https://user-images.githubusercontent.com/12643380/33839183-dd9ce712-de91-11e7-9f96-9e6ea8280657.png">

Here are my styles for it:
```{
  input: {
    outline: 0,
    border: 0,
    paddingTop: '1px',
    maxHeight: '100px',
    overflow: 'auto',
    minHeight: '50px'
  },
};```

**Comment by jfschwarz** [comment]
Currently the component is not really prepared to allow scrolling. It should be possible to make it scrollable by setting `max-height` and `overflow` styles on the container `div` so both, the textarea and the highlighter `div`, elements are scrolled together. I haven't really tried this out yet, though. Let us know if you find a solution.
