### ISSUE TITLE
How can i focus the textarea after change the value props.

### ISSUE THREAD

**Issue by luofei2011** [signavio/react-mentions#219]
```
constructor() {
  super();
  this.state = {value: ''};
}
doMention = () => {
  this.setState({value: "@[someone](id)});

  // TODO 
  // how to focus the `MentionsInput`?
}
```

**Comment by jfschwarz** [comment]
You have to somehow get hold of the `textarea` element and then call its `.focus()` method. We are planning to allow passing an `inputRef` prop which will be forwarded as a ref to the textarea. This extension is planned with the next major release, which you can expect in about 2 weeks.

Until then you could just try with a `ref` or `findDOMNode` in your wrapping component and select the inner `textarea` element from there.

**Comment by stevesuh** [comment]
Any progress on this?  I'm looking at the latest source code and I don't see support for it.

**Comment by luofei2011** [comment]
@stevesuh 

This is my solution:
```
<MentionInput className="x-custom-ipt" {...otherProps}>
  <Mention />
</MentionInput>
```

After that, The `textarea` element will has the className `x-custom-ipt__input`. you can also find and focus it by:

```
document.querySelector('.x-custom-ipt__input').focus();
```

**Comment by tanmoy-airbase** [comment]
@jfschwarz @luofei2011 tried using inputRef by calling `.focus()` it is focusing correctly but not rendering the suggestions list

**Comment by tanmoy-airbase** [comment]
Hey @jfschwarz @luofei2011 @frontendphil @atilafassina, I am stuck on the above issue and seeking your help. Thank you!
