### ISSUE TITLE
Position offset of popup menu and highlight area

### ISSUE THREAD

**Issue by yangke687** [signavio/react-mentions#222]
![image](https://user-images.githubusercontent.com/24886188/35734361-d5cd3926-085b-11e8-8feb-2affd4700848.png)
![image](https://user-images.githubusercontent.com/24886188/35734429-11b75dae-085c-11e8-9d79-961a19fcbe20.png)
![image](https://user-images.githubusercontent.com/24886188/35734445-2207920a-085c-11e8-859d-b543bff863a9.png)
When I typed some text, there appears position offset of the selection dropdown menu and highlight area.

**Comment by rubencodes** [comment]
Are you possibly adding padding to the textarea? I had this issue and that was what was wrong. I instead wrapped it in a div and added padding there.

**Comment by yangke687** [comment]
@rubencodes 
![image](https://user-images.githubusercontent.com/24886188/35761851-c31a5c24-08c8-11e8-88cc-a2d1e27aaa5d.png) The problem exists still.

**Comment by yangke687** [comment]
![image](https://user-images.githubusercontent.com/24886188/35790380-0561ae88-0a7d-11e8-89ba-021625a1aef5.png)
This is due to the Fixed-width fonts and 'font-size' has been set to '1rem', the caret span dom has been stretched.
