### ISSUE TITLE
Default Suggestion Sorting

### ISSUE THREAD

**Issue by niknokseyer** [signavio/react-mentions#223]
On the async example, there is sorting involved:
```
function getHashtags(query, callback) {
  const getIndex = tag => tag.indexOf(query.toLowerCase());
  fetch('data/hashtags.json')
    .then(res => res.json())

    // Note: the following two lines aren't needed if your data source already
    // filters and/or sorts results
    .then(tags => tags.filter(tag =>  getIndex(tag) !== -1))
    .then(tags => tags.sort((a, b) => getIndex(a) - getIndex(b)))

    // Transform the hashtags to what react-mentions expects
    .then(tags => tags.map(tag => ({ display: tag, id: tag })))

    .then(callback)
}
```

Is it possible to add this kind of sorting when `data` provided is just an array?

**Comment by frontendphil** [comment]
Hey @niknokseyer when data is just an array, you can simply sort that array the way you like and pass that into the component.

**Comment by niknokseyer** [comment]
Is there a way to do the sorting similar to async @frontendphil?

Here's an example:

<img width="165" alt="screen shot 2018-02-12 at 5 51 35 pm" src="https://user-images.githubusercontent.com/2403463/36129746-8b2b46d2-101d-11e8-844d-9c72d43ed414.png">

With sorting like the `async` Saul and Skyler will be the top results. Not Jesse or Gustavo.

Worse case I'm thinking of doing it via`function (search, callback)` to do the sorting and then return the sorted array. Just not sure if that's efficient or makes any sense.

**Comment by frontendphil** [comment]
If you want something sorted, the sorting has to happen at some point. `react-mentions` simply makes no assumptions and shows the data it is provided. Sorting a list with a couple of entries before handing it to the `callback` function won't hit your performance.
