### ISSUE TITLE
wrappedInstance.clearSuggestions();

### ISSUE THREAD

**Issue by vonubisch** [signavio/react-mentions#224]
The function `clearSuggestions()` housed in ref `this.mentionInput.wrappedInstance` is not doing anything.
Also it is undocumented, like every other function in the `ref` object.

**Comment by frontendphil** [comment]
It is undocumented because it is not part of the public API. In general your code shouldn't rely on any methods on the react instance or the react instance in general. 

What is it you're trying to do? Or: is something not working?

**Comment by vonubisch** [comment]
I browsed the issues and found issue #193, user @gbsandeep posted a solution for adding mentions via code. This worked perfectly and I was curious about other functions that were available. 
I explored the `wrappedInstance` object and found the `clearSuggestions()` function.

I want to clear all text and/or mentions from the textarea.

**Comment by jfschwarz** [comment]
Just pass down the empty string as the new `value` for clearing the entire content of the textarea. For removing all mentions / only the text between mentions you should be able to implement a regexp replace with a rather low effort. 

It is really a bad idea to access `wrappedInstance`.  Don't do it.
