### ISSUE TITLE
Expose utils functions as public API

### ISSUE THREAD

**Issue by manzoo** [signavio/react-mentions#229]
Hi,

Could the utils functions be exported as public API.
We have a requirement to capture all the mentions seperately and send email.

We are interested in the following functions of utils.
`getMentions` , `makeMentionsMarkup` and `getPlainText`

Regards,
Manju

**Comment by jfschwarz** [comment]
It's definitely a possibility to expose certain util functions as public API. However, we try to keep the API surface minimal, so I would really decide on a case-by-case basis if it really necessary to publicly export a util function.

Can you explain for what purpose exactly you would need `getMentions, and `getPlainText`? Did you notice that both, the plain text value and the array of mentions, are already passed as arguments to the `onChange` handler (see https://github.com/signavio/react-mentions#configuration)?

As for the  `makeMentionsMarkup` function, I believe that it is so simple that you can simply copy paste it. If we would ever change the placeholder syntax, it would definitely be considered a breaking change and only happen with a major release. So no worries about that.

**Comment by manzoo** [comment]
@jfschwarz Thank you for the quick reply.

I overlooked the `onChange` arguments. I can use that event to capture what i needed and complete the functionality.

I will consider your suggestion for `makeMentionsMarkup` function.

**Comment by filippofilip95** [comment]
@jfschwarz Now I'am solving different use case where I need to access utils functions.

My use case is to insert emoji (from list outside) into textarea with mentions.

If the caret is inside of mention and I'm adding emoji, I need to avoid inserting emoji into the middle of plain text mention value. To accomplish this I need to find the start of mention and place emoji before the plain value of mention.

For this I'm using methods `mapPlainTextIndex` and `findStartOfMentionInPlainText` which are not accesible in version `3.1.0`. 

I found a quick workaround described in #193. But it's not a long term solution.

Will keep utils functions still private for the future?
