### ISSUE TITLE
suggestions container rerender

### ISSUE THREAD

**Issue by dingdingbai** [signavio/react-mentions#231]
Hi, thanks for this awesome library. But I met a problem during use this library
Here is my code
![image](https://user-images.githubusercontent.com/19373581/37073663-45b7734e-2203-11e8-8488-73aabb00f60a.png)
and I will get remote data in `searchUser` function, the problem is every time I input the query the whole suggestion container will be rerendered. Is there a way just render the suggestion list but not the whole container(e.g:facebook). 
![test](https://user-images.githubusercontent.com/19373581/37073863-539f2b36-2204-11e8-88ca-12cf28452d3d.gif)

expected behavior:
![test1](https://user-images.githubusercontent.com/19373581/37074055-aa8a6766-2205-11e8-8a59-44960ef413ff.gif)

**Comment by dingdingbai** [comment]
After I reading the src script, I notice  that in `MentionsInput.js`, `updateMentionsQueries` function(line: 520)
```
updateMentionsQueries = (plainTextValue, caretPosition) => {
    // Invalidate previous queries. Async results for previous queries will be neglected.
    this._queryId++
    this.suggestions = {}
    this.setState({
      suggestions: {},
    })

***
```
It will set `suggestions` to empty Object every time I input new query.
I was wondering whether we can assign `suggestions` a new object only when the `plainTextValue` is empty.

The issue I mentioned is not a bug, but I think it would be better by preventing update `suggestions` to an empty object during updating mentions queries.

**Comment by jfschwarz** [comment]
The clearing of the `suggestions` is important so that there will never be stale results. 

Instead, you should enhance your `searchUser` function so that it keeps a cache of previously fetched results. The callback that `searchUser` receives can be invoked multiple times, so you can invoke it synchronously with a filtered array of the previous results, and another time once the updated search request is completed and you have your new results.

 Hope this helps.

**Comment by dingdingbai** [comment]
Thank your for the suggestion! I’ll have a try!




    
    
    



    
        
            
                
                    
                        
                    
                    
                        
                            bai dingding
                            
                            
                                
                                    邮箱：dingdingbai0424@gmail.com
                                
                        
                    
                
            
        
    


签名由 网易邮箱大师 定制
On 03/07/2018 17:55, Jan-Felix wrote: The clearing of the suggestions is important so that there will never be stale results.
Instead, you should enhance your searchUser function so that it keeps a cache of previously fetched results. The callback that searchUser receives can be invoked multiple times, so you can invoke it synchronously with a filtered array of the previous results, and another time once the updated search request is completed and you have your new results.
Hope this helps.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/signavio/react-mentions","title":"signavio/react-mentions","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/signavio/react-mentions"}},"updates":{"snippets":[{"icon":"PERSON","message":"@jfschwarz in #231: The clearing of the `suggestions` is important so that there will never be stale results. \r\n\r\nInstead, you should enhance your `searchUser` function so that it keeps a cache of previously fetched results. The callback that `searchUser` receives can be invoked multiple times, so you can invoke it synchronously with a filtered array of the previous results, and another time once the updated search request is completed and you have your new results.\r\n\r\n Hope this helps."}],"action":{"name":"View Issue","url":"https://github.com/signavio/react-mentions/issues/231#issuecomment-371085251"}}}

**Comment by dingdingbai** [comment]
Thank you for the suggestion! I'll have a try
