### ISSUE TITLE
Change the style for the mentioned

### ISSUE THREAD

**Issue by hazemkiwan** [signavio/react-mentions#233]
Hi,

I am using the react mention,  and what i want is to  change the design for the mentioned value after selected it from the list.

i used the displayTransform
`displayTransform={ (id, display, type) => type === 'user' ? `@${id} ` :`#${id} ` }
`
What i need is to make the @user1 with color red in the text are after selected. and #hashtag1 with color green in the text area, how can fix this issue please?

Note: i tried to use this code 
`displayTransform={ (id, display, type) => (<div className="test-class">{type === 'user' ? `@${id} ` :`#${id} `}</div> )}`
but i did not work

**Comment by jfschwarz** [comment]
`displayTransform` can only return a string value, no React elements. For changing the highlighting color, set `className` or inline `style` prop on the `<Mention />` element. Check the example here: https://github.com/signavio/react-mentions/blob/master/demo/src/examples/MultipleTrigger.js#L43
