### ISSUE TITLE
Manually Trigger Suggestion

### ISSUE THREAD

**Issue by deeajay123** [signavio/react-mentions#237]
Manually/programmatically trigger the suggestion

**Comment by jfschwarz** [comment]
Sorry, I don't understand what you mean. Please try to describe your problem in more detail.

**Comment by delgermurun** [comment]
Hello @jfschwarz 

I have same question with @deeajay123.

Here is my situation. I have 2 collections with parent, child relationship. Like:
```
parent1
  child11
  child12
parent2
  child21
  child21
```

I want to show only parents first on suggestion dropdown selector. When user clicked/selected one parent, then only show selected parent's children again. Then finally user can mention one of children.

Btw, I will not mention parent, only mentions child. Selecting with 2 steps is only for UX.

How can I do something like that? Do you have any suggestion?

One possible solution I can think of is, maybe I can trigger children mention component programmatically on parent mention component's `onAdd` event.

Thanks.
