### ISSUE TITLE
displayTransform is called multiple times after insert. 

### ISSUE THREAD

**Issue by Plukers** [signavio/react-mentions#238]
Hey, first of all, thank you for the great project!! 
I have an issue regarding displayTransform:

Following setup:
```javascript
      <MentionsInput
        value={this.props.value}
        placeholder={this.props.placeholder}
        onKeyDown={this.props.onKeyDown}
        onChange={this.props.onChange}
        disabled={this.props.disabled}

        displayTransform={(id, display, type) => {
          console.log(id, display, type);
          let transformed = '';
    
          switch (type) {
            case 'USER_MENTION_TYPE':
              transformed = `@${display}`;
              break;
            default:
              transformed = display;
          }
          return transformed;
        }}

        style={mentionsInputStyle}
      >
        <Mention
          trigger="@"
          type="USER_MENTION_TYPE"
          data={this.fetchUsers}
          onAdd={this.props.onUserAdd}
          style={mentionStyle}
        />
      </MentionsInput>
```

The `displayTransform` function does not work correctly. It's called multiple times with a wrong input after a mentioning.
Here is the console output of the `console.log` in `displayTransform` after mentioning `testUser_0`:

```
users/testUser_0 testUser_0 USER_MENTION_TYPE
users/testUser_0 testUser_0 testUser_0
users/testUser_0 testUser_0 null
users/testUser_0 testUser_0 null
users/testUser_0 testUser_0 testUser_0
users/testUser_0 testUser_0 null
users/testUser_0 testUser_0 null
users/testUser_0 testUser_0 null
users/testUser_0 testUser_0 null
users/testUser_0 testUser_0 testUser_0
users/testUser_0 testUser_0 null
users/testUser_0 testUser_0 null
```
The type is correct the first time, then it alternates between `null` and `display`

This output continues when I click into the textbox and outside the textbox.

Click inside the textbox:
```
users/testUser_0 testUser_0 null
users/testUser_0 testUser_0 null
users/testUser_0 testUser_0 testUser_0
users/testUser_0 testUser_0 null
users/testUser_0 testUser_0 null
```

Click outside the textbox:
```
users/testUser_0 testUser_0 testUser_0
users/testUser_0 testUser_0 null
```

Thank you very much in advance for your help!

**Comment by Plukers** [comment]
After I added the `markup="@[__display__](__type__:__id__)"` from the examples the function is still called multiple times, but now it's always with the correct input.

**Comment by frontendphil** [comment]
Hey @Plukers you basically figured it out yourself. Even though I can't, from the top of my head, explain why the `type` param is set only sometimes when the `markup` is not correct it is perfectly normal, that the `displayTransform` method is called multiple times. The method is used internally to determine all kinds of things to get the layout right. 

Do you experience any issues regarding this behavior?

**Comment by Plukers** [comment]
Hey @frontendphil, no, I'm not having any issues regarding this behavior. I just didn't know that it was normal and wanted to mention it.

Anyway, thank you for your answear!

**Comment by frontendphil** [comment]
No problem at all. If there is nothing further, I'll go ahead and close the issue.
