### ISSUE TITLE
How to return HTML element into displayTransform

### ISSUE THREAD

**Issue by hazemkiwan** [signavio/react-mentions#239]
While using react-mentions i tried to return an HTML element into displayTransform, here is my code:

`displayTransform={ (id, display, type) => type === 'admin' ? `$${id} ` :`@${id} ` }`

What i want is to make $${id} into an html element Just like that:

`displayTransform={ (id, display, type) => type === 'admin' ? <span>`$${id} `</span> :`@${id} ` }`

So, what should i do please?

**Comment by jfschwarz** [comment]
You cannot render return HTML elements in a `displayTransform` function. That function is only for modifying the plain text of a mention in the textarea. react-mentions is built around a regular `<textarea />` element, which cannot have HTML elements as content. If you want to change the background color or other styles of the mentions highlighting, you can do so by passing a `style` or `className` prop to the `<Mention />` element. Also see https://github.com/signavio/react-mentions#styling
