### ISSUE TITLE
What's new in v2?

### ISSUE THREAD

**Issue by rubencodes** [signavio/react-mentions#243]
Not a bug, just a question—I saw this was updated to v2+, I was wondering (since this project follows semver) what are the breaking changes if any? Would be awesome if there were a Changelog.md!

**Comment by jfschwarz** [comment]
breaking changes are documented in the release notes: https://github.com/signavio/react-mentions/releases/tag/v2.0.0

**Comment by rubencodes** [comment]
Ah, thank you! My bad for missing that 😅
