### ISSUE TITLE
Let trigger work despite lack of preceding space 

### ISSUE THREAD

**Issue by jakey-wan-kenobi** [signavio/react-mentions#244]
**Steps to reproduce:**

1. Add a trigger to your component (for example, a "{" character)
2. Start typing a string, and without adding a space, type the trigger character of "{"

**Desired behaviour:**
Show the suggestions, despite the lack of a preceding space. When a suggestion is selected, just replace the part of the string after the "{" character. 

**Observed behaviour:**
The trigger only works if it's a new word/string.

**Workaround:**
No workaround as far as I can see.

Thanks!

**Comment by jfschwarz** [comment]
To achieve this, you can pass a regexp for the `trigger` prop. Check out the MultipleTrigger example: https://github.com/signavio/react-mentions/blob/master/demo/src/examples/MultipleTrigger.js#L40
