### ISSUE TITLE
How can I add padding to the mention ??

### ISSUE THREAD

**Issue by Rohanhacker** [signavio/react-mentions#245]
Using style = {{
  backgroundColor: "rgba(145,213,255, 0.3)",
 padding: 5     
}} 
in Mention messes up the alignment.

**Comment by jfschwarz** [comment]
The highlighting is realized by duplicating the content of the `textarea` in a `div` behind it. So it is crucial that the styling of these elements is the same, otherwise, you will see alignment problems.

You could experiment with negative margins:

```
style = {{
  backgroundColor: "rgba(145,213,255, 0.3)",
  padding: 5,
  margin: -5
}}
```

**Comment by Rohanhacker** [comment]
@jfschwarz Thanks worked for me

**Comment by steve-cahn** [comment]
This solution covers the text before and after.

**Comment by vittaljk** [comment]
> This solution covers the text before and after.
Give only top and bottom padding to highlight and left and right spacing can be given by using displayTransform,

`style = {{
  backgroundColor: "rgba(145,213,255, 0.3)",
  padding: 3px 0;
}}`

`<Mention
          data={data}
          displayTransform={(_, display) => `       @${display}        `}
          ....
 />`
