### ISSUE TITLE
Trigger suggestions on *any* key

### ISSUE THREAD

**Issue by salpulse** [signavio/react-mentions#248]
Is it possible to trigger/(trick) MentionsInput to fire up the suggestions upon any key press and include that keystroke in the suggestions? I'm trying to implement a names typeahead field which doesn't need a @ key to start and only accepts names.

**Comment by frontendphil** [comment]
Have you tried passing a `RegExp` as a trigger that simply matches everything?

**Comment by antoniopacheco** [comment]
I was able to replicate:
on MentionInput.js line 602:
`_this3.queryData(match[2], child, querySequenceStart, querySequenceStart + match[1].length, plainTextValue);`
if the regexp is \.\ .  (any character)
 match length is only 1, so match[1] and match[2] won't exist
throwing an error 
![image](https://user-images.githubusercontent.com/6589732/44496720-9ac15980-a62a-11e8-9a1a-a2c925833585.png)

**Comment by jfschwarz** [comment]
That is because your regexp does not define any capturing groups. Try using:

```
// first capture group is the part to be replaced on completion
// second capture group is for extracting the search query
const trigger = /((.*))/
```
