### ISSUE TITLE
Cordova iOS Issue

### ISSUE THREAD

**Issue by spacepotato** [signavio/react-mentions#249]
**Steps to reproduce:**
Clicking on a suggestion does not correctly select it

1. Enter trigger key (eg @) 
2. Click on suggestion

**Expected behaviour:**
The clicked suggestion appears in the text area

**Observed behaviour:**
The suggestions overlay closes with nothing being selected.

**Workaround:**
The issue appears to be caused by the `onMouseDown` event not firing. The fix we came up with was to replace the `onMouseDown` event in `SuggestionsOverlay#render()` with an `onClick()`.
In addition to this we also wrapped the contents of `MentionsInput#onBlur()` in a timeout as onBlur fires before the suggestions overlay click event.

**Comment by jfschwarz** [comment]
If I remember correctly, we switched from `onClick` to `onMouseDown` because of race conditions with `onBlur`. So applying the fix you suggested would most probably break it on other platforms.

It seems wrong that `onMouseDown` is not triggered. Did you investigate why?
