### ISSUE TITLE
I can't paste text in Safari. In other browsers works normally

### ISSUE THREAD

**Issue by Rabinzon** [signavio/react-mentions#250]
**video:** 
Safari: http://take.ms/H82ER
Chrome: http://take.ms/H82ER 
**Steps to reproduce:**
1. open safari 
2. set value via setState in to MentionInput 
3. copy and paste something to textarea  
event.target.value receiving in handleChange looks like :
```
 @admin [wrote](#c_123): 
> my comment 


> my comment 
```
In the same time textarea value is correct: 
```
@admin [wrote](#c_123): PASTED TEXT 
> my comment 
```

I have no idea how to fix this:( 
**Workaround:** MacOS 10.13.4 Safari 11.1

**Comment by jfschwarz** [comment]
Do you see the same problem on our demo page https://signavio.github.io/react-mentions/master/ ?

**Comment by Rabinzon** [comment]
@jfschwarz It's not actual now. You can close this issue. Thanks!
