### ISSUE TITLE
Cursor keeps jumping to the end of the input when the selector is in the middle of the value

### ISSUE THREAD

**Issue by liamhubers** [signavio/react-mentions#253]
**Steps to reproduce:**

1. Create an input wrapped by `redux-form`, only works in React 16
```
import React, { Component } from 'react';
import { connect } from 'react-redux';
import { Field } from 'redux-form';
import { MentionsInput, Mention } from 'react-mentions';

class MentionsInput extends Component {
  static propTypes = {
    input: PropTypes.object.isRequired,
  }

  constructor() {
    super();

    this.handleChange = this.handleChange.bind(this);
    this.handleSearch = this.handleSearch.bind(this);
    this.transformMention = this.transformMention.bind(this);
  }

  handleChange(e) {
    const { onChange } = this.props.input; // redux-form
    const { value } = e.target;

    onChange(value);
  }

  handleSearch(query, cb) {
    // send to RxJS
  }

  transformMention(id) {
    return id; // fake
  }

  render() {
    const { placeholder, input: { value } } = this.props;

    return (
      <MentionsInput
        allowSpaceInQuery
        className="Form__control"
        markup="@(__id__)"
        value={value}
        placeholder={placeholder}
        onChange={this.handleChange}
        displayTransform={this.transformMention}
      >
        <Mention
          appendSpaceOnAdd
          trigger="@"
          data={this.handleSearch}
          renderSuggestion={(user) => user.full_name}
        />
      </MentionsInput>
    );
  }
}

const mapStateToProps = (state) => ({
  extraData: {}, // fake
});

export default connect(mapStateToProps)((props) => <Field {...props} component={MentionsMentionsInput} />);
```
2. Type some random text in the input `test 123 test`
3. Try and remove the `123` in the above text

**Expected behaviour:**
Should be able to remove text anywhere in the input.

**Observed behaviour:**
When I try to remove text (with backspace) in the middle of the current value it removes one character and then puts the cursor at the end of the input.

**Workaround:**
It's because of this issue in React https://github.com/facebook/react/issues/12762 .

I think this issue is caused by `redux-form`, as they add a small delay before updating the input, making `React` believe the value hasn't been changed and the case as explained in the issue above gets triggered.

I've managed to fix this by storing all values coming through the `onChange` in the state of `MentionsInput` before passing it to the `onChange` passed by `redux-form`. This eliminates the small delay `redux-form` causes.

I'm not sure if this is your responsibility to fix or not, but I thought I'd post it as an issue anyway.

**Comment by jfschwarz** [comment]
Thanks for reporting. If MentionsInput behaves the same as the React input, I think we should not change anything. We should keep an eye on the discussion at https://github.com/facebook/react/issues/12762, though.
