### ISSUE TITLE
npm out of sync with source?

### ISSUE THREAD

**Issue by activescott** [signavio/react-mentions#254]
I was using the package from npm and just pulled the source and noticed some differences.

~~1. Mention style didn't work anymore~~ (nevermind that was my bad)
2. The refs are not stored the same way (I need a ref to the actual input control).

Since I don't see version/release branches, I'm hoping that master is just more current than npm and we should investigate and fix any bugs here. Is that correct?

**Comment by jfschwarz** [comment]
I just checked and v2.1.0 published to npm is in sync with latest master afaict. 

Regarding point 2: You can currently only get hold of a ref to the input element using private API. Could you describe what you need the ref for?

**Comment by activescott** [comment]
Thanks for the response. The reason I need the ref is that I'm integrating with an app that has some non-react code and it needs to set focus to the input control directly so I need that node.
