### ISSUE TITLE
Unselectable suggestions

### ISSUE THREAD

**Issue by johnnyodonnell** [signavio/react-mentions#256]
I would like to add the ability to make a suggestion unselectable. For example, I would like to show error messages and loading messages in the SuggestionsOverlay without worrying about a user clicking them and creating a mention. I don't mind implementing this myself and then creating a pull-request with the necessary tests and documentation, but wanted to discuss here first to see if you guys were interested in this.

Here is an example of what I am thinking: https://github.com/johnnyodonnell/react-mentions/commit/d1075af20defe691479840640dbd6835238a439a

**Comment by johnnyodonnell** [comment]
Any thoughts on this?

**Comment by johnnyodonnell** [comment]
Cool, the discussion in that issue helps. What are `header` and `footer` elements? Can elaborate on that or point to some documentation?

**Comment by jfschwarz** [comment]
`header` and `footer` elements are not supported yet. It's just an idea we'd like to evaluate. The question is if it would be sufficient for your use case to render arbitrary React elements before and/or after the list of suggestions.

**Comment by johnnyodonnell** [comment]
Yes, I think that would indeed satisfy my use case. Should I create an issue to track the work for `header`/`footer`?

**Comment by jfschwarz** [comment]
Suggestions headers/footers are tracked here: https://github.com/signavio/react-mentions/issues/65
