### ISSUE TITLE
Is Ract Mention support SHIFT+ENTER to add New Line

### ISSUE THREAD

**Issue by nevetushar** [signavio/react-mentions#263]
Is there any way so if i press SHIFT+ENTER  Ract Mention will add new Line.
and if Only Enter is pressed it will submit the form.

I want to make component like SLACK chat,

Thanks

**Comment by jfschwarz** [comment]
Sure, you can build this with `<MentionsInput onKeyDown={this.handleKeyDown} />` just like you would do it with a regular `<textarea />` element.

**Comment by nevetushar** [comment]
Thanks

**Comment by TallOrderDev** [comment]
@jfschwarz to prevent race conditions with onChange, could we expose the event as the event argument already on the onChange? With the way the docs work, I thought we should have already been giving out this info.
