### ISSUE TITLE
Auto mention when there is only one matched entry

### ISSUE THREAD

**Issue by qhuyduong** [signavio/react-mentions#266]
Hi,
First of all I would like to give great thank to your component. It's perfect.

I have a desired behavior like this: after user triggers the mention and types in some characters, when there is only one match result in suggestion, if user presses SPACE, that only match result will be marked as a mention automatically.

Is it possible to achieve this?
Thanks.

**Comment by kashifshamaz21** [comment]
@qhuyduong I do think this is possible, but until then, just wanted to check with you if the current behaviour doesn't help -- when the suggestions list opens, the first suggestion is automatically in focus, so pressing an `Enter` keystroke at that point would automatically select the first suggestion. So in the case where there is only one suggestion, the user just needs to press Enter once and the first & only suggestion will get selected.
