### ISSUE TITLE
Add TypeScript definitions to the package

### ISSUE THREAD

**Issue by activescott** [signavio/react-mentions#268]
I have a rough set of TypeScript definitions that I am using for this component that I think would be great to add directly to the package for those of us using it in TypeScript. This will make the props strongly typed and the only "cost" would be that when props are added or changed, the type definition in this single additional file would need updated.

Will you be willing to merge the PR if I put it together per the [guidelines prescribed in the TypeScript Handbook](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html)?

**Comment by jfschwarz** [comment]
Sure, this sounds like a great addition! We'd be glad to accept a PR.

**Comment by activescott** [comment]
Thanks for the reminder. I'll push this today or tomorrow

**Comment by activescott** [comment]
@omkar-joshi I have a WIP branch for this in my fork at [activescott/react-mentions/tree/268-add-typescript-definitions](activescott/react-mentions/tree/268-add-typescript-definitions). I want to create a test a couple things -including using this package in an existing project to see how it migrates. It will be great if you can do some testing with it and confirm for me that it works for you.

**Comment by activescott** [comment]
I have submitted a PR to DefinitivelyTyped at https://github.com/DefinitelyTyped/DefinitelyTyped/pull/29773 once accepted we should all be able to start using `yarn add @types/react-mentions`

Some notes I found useful:
- https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html
- http://definitelytyped.org/guides/best-practices.html
- http://definitelytyped.org/guides/contributing.html

**Comment by activescott** [comment]
[PR merged](DefinitelyTyped/DefinitelyTyped#29773) and has been merged to master at https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react-mentions 

Has been published to NPM at https://www.npmjs.com/package/@types/react-mentions 🎉  So I am resolving this issue.
