### ISSUE TITLE
Not able to set style(hover) to mention 

### ISSUE THREAD

**Issue by sanketgandhi876** [signavio/react-mentions#270]
Thank you for amazing lib. I need help regarding applying CSS.

Whenever user hover over list then mention component will set background color to blue and name appears in white but the title remains the same. Title which is appearing in gray should get white too.

Here is code: https://codesandbox.io/s/n5n6jm7k6j

Thanks for the help

**Comment by jfschwarz** [comment]
Hmm, this is a good question. :) I also have no idea how to do it in the current state of the implementation. 

To support this we'll have to extend the `Suggestion` component a bit. I'd suggest passing `this.props.focused` as the last argument of the `renderSuggestion` call here: https://github.com/signavio/react-mentions/blob/master/src/Suggestion.js#L43. This way we avoid a breaking API change. Do you care to submit a PR for this?

**Comment by sanketgandhi876** [comment]
Sure, will submit PR. But is there any workaround for now?

**Comment by jfschwarz** [comment]
Well, my only idea would be using css instead of inline styles. Then you can use a nested selector.

**Comment by sanketgandhi876** [comment]
I tried it but unable apply hover color on title. If you don't mind then could you please show me an example in codesandbox :)

Existing code: https://codesandbox.io/s/n5n6jm7k6j

**Comment by jfschwarz** [comment]
Gimme a sec, I will add the extra argument to the `renderSuggestion` function right now

**Comment by sanketgandhi876** [comment]
Awesome! It's working. Thanks @jfschwarz 
Once PR is merged, I'll push my code to prod and will send example to you guys. 

**Suggestion**: In README add example section where everybody can access those examples(maybe codesandbox link or repo) for different use cases :)

**Comment by sanketgandhi876** [comment]
Hey @jfschwarz 
I have a question, can I wrap textarea with other components? 
So for e.g., I have rich-text area (like [Quill](https://quilljs.com/)) whenever user start typing '@' then `reac-mentions` will render the user list and once user is selected, user name will render to rich-text area (so that I can post process the text to the hyperlink). 

Thanks

**Comment by jfschwarz** [comment]
I'm afraid this is not possible and also won't be s.th. we will support in the future. The reason is, that react-mentions is designed to take full control of the underlying textarea. If you want to use a rich text editor you're better off building up on that component to show suggestions.

**Comment by sanketgandhi876** [comment]
Got it. Thanks
