### ISSUE TITLE
Cursor sometimes jumps to the end randomly when editing text in between

### ISSUE THREAD

**Issue by hashwin** [signavio/react-mentions#274]
**Steps to reproduce:**

I created a minimal implementation of react-mentions to demonstrate the issue:
https://github.com/hashwin/react-mentions-example/blob/master/src/App.js

See the following reproduction from that:
![screencast-localhost-3000-2018 09 20-14-22-21](https://user-images.githubusercontent.com/406115/45807954-3ef9f700-bce2-11e8-8b74-fadc08551283.gif)

**Expected behaviour:**
Cursor should never jump

**Observed behaviour:**
Cursor jumps randomly, adding a linebreak and sometimes a character too (not necessarily the key pressed either, it weirdly seems to be the first character of the next line)

**Workaround:**
None

**Comment by jfschwarz** [comment]
I cloned your repository, but I cannot reproduce the recorded behavior. I tried with long content on Chrome, Safari with Grammarly plugin, and Firefox (Mac). Please provide a more detailed description of the environment needed for reproducing the bug.

**Comment by hashwin** [comment]
MacOS High Sierra 10.13.6
Chrome Version 69.0.3497.100
I can reproduce on Firefox too.
This also happens on the Chrome Browser of my Android device.

I don't think it is related to the Grammarly plugin as this bug has been reported in my app fro users on different environments too.

**Comment by hashwin** [comment]
FWIW it seems to happen more frequently on mobile devices.
On the browser, it seems to be limited to when you click and type quickly.

See reproduction on my Android (HTC U11 Oreo 8.0)

https://www.youtube.com/watch?v=LXUW2qEszPE

**Comment by hashwin** [comment]
@jfschwarz Were you able to reproduce it? Please let me know if you need any further evidence or direction on how it can be reproduced.
