### ISSUE TITLE
error if ID property in the data is 0

### ISSUE THREAD

**Issue by AmihaySchwarz** [signavio/react-mentions#277]
**Steps to reproduce:**

1. Create an array 
2. like this` [{id:0,display:"A"},{id:1,display:"B"}]`

there is an error processing it in line 13, where the !id === 0 return false:
```

1. Suggestion.prototype.getDisplay = function getDisplay() {
2.     var suggestion = this.props.suggestion;
3. 
4. 
5.     if (suggestion instanceof String) {
6.       return suggestion;
7.     }
8. 
9.     var id = suggestion.id,
10.         display = suggestion.display;
11. 
12. 
13.     if (!id || !display) {
14.       return id;
15.     }
16. 
17.     return display;
18.   };

```

**Expected behaviour:**

**Observed behaviour:**
exception in runtime
**Workaround:**
dont use id === 0

**Comment by frontendphil** [comment]
It does look like you've found the respective code point already and we'd be happy to accept a PR for this1

**Comment by WxnChen11** [comment]
Please see #290
