### ISSUE TITLE
Is is possible to get underlying input node ref?

### ISSUE THREAD

**Issue by O4epegb** [signavio/react-mentions#278]
Is is possible to get underlying input node ref?
For example, I want to be able programmatically focus input.

**Comment by frontendphil** [comment]
We do keep refs internally already. @jfschwarz should we use `forwardRef` and the likes or should we turn those parts of the implementation into a public API?

**Comment by jfschwarz** [comment]
I would suggest adding support for a prop called `inputRef`. The reason I prefer that over using `forwardRef` is that we have multiple elements (input, suggestions drop-down) the user might want to get a handle of so it wouldn't be obvious to the user where the passed ref is forwarded to.

**Comment by jfschwarz** [comment]
I just have a moment of free time and I'm going implement the `inputRef` prop now...

**Comment by O4epegb** [comment]
Awesome, thank you! Gonna try it this week!
