### ISSUE TITLE
Shift background on mentions

### ISSUE THREAD

**Issue by ThibautMarechal** [signavio/react-mentions#282]
Hi i'm having some problem when i use react-mention in my project. 
I can reproduce this issue in the example page.
I think that the width of the scrollbar is the problem not handle in react-mentions.

**Steps to reproduce:**

1.  use textarea input (multiline)
2.  insert very long word, or just mentions 

**Expected behaviour:**
The background should be place behind the corresponding mentions

**Observed behaviour:**
![issue2](https://user-images.githubusercontent.com/20936586/48260560-25d91100-e41c-11e8-8174-aca8ee2b520b.PNG)
![issue1](https://user-images.githubusercontent.com/20936586/48260562-2671a780-e41c-11e8-9715-10af234e6be8.PNG)

**Workaround:**
none

**Comment by mkamka** [comment]
i had kind of a similar issue, but it was caused by a global css letter-spacing property. Setting the letter-spacing to same value for multiline input style fixed it.
