### ISSUE TITLE
How to submit data once stored in state?

### ISSUE THREAD

**Issue by edPratt** [signavio/react-mentions#283]

**Comment by frontendphil** [comment]
@edPratt you do realize that we can't do anything if you don't at least try to come up with a proper description of what is not working?

**Comment by edPratt** [comment]
@frontendphil 
I have an input element inside of a form that has an onSubmit prop passed to it that handles (obviously) submitting the input data. How can I provide Mention ability within that input element, or is there some way to provide an onSubmit to the MentionsInput.
