### ISSUE TITLE
Consider removing lodash

### ISSUE THREAD

**Issue by goenning** [signavio/react-mentions#284]
When looking at https://bundlephobia.com/result?p=react-mentions@2.4.0, it seems like 59% of react-mentions package is lodash. There's is more lodash code than react-mentions itself.

Lodash has been a dependency since 0.3.0 (~ 2 years ago) and a lot has changed since.

I found 6 lodash functions being used: 

| Lodash  | Suggestions |
| ------------- | ------------- |
| omit  | var { a, b, ...result } = object;  |
| keys  | Object.keys  |
| isEqual  | hand written alternative using ===  |
| isNumber  | typeof value === 'number' |
| isFinite  | Number.isFinite  |
| values  | Object.values  |

There might be better alternatives, these are just suggestions.

Some of these are not cross-browser compatible, that is truth, but polyfills is very common (and expected) for apps that need to support other browsers. The rest operator is transpiled by Babel/TypeScript into valid ES5 code. We don't need to push all these lodash functions to browsers that have this built-in. 

Without lodash, this package could be reduced to ~40kB, that's a ~50% reduction.

Any thoughts?

**Comment by jfschwarz** [comment]
Absolutely, we haven't looked into optimizing bundle size at all so far. Your suggestions make a lot of sense. We would be happy to accept PRs.

**Comment by zenVentzi** [comment]
Any updates on the issue? Using v. 2.4.1

**Comment by frontendphil** [comment]
Nope, but we're happy to accept PRs ;)
