### ISSUE TITLE
displayTransform function return incorrect "display" value

### ISSUE THREAD

**Issue by wesleywong** [signavio/react-mentions#286]
```javascript
displayTransform = (id, display, type) => {
	console.log('id : '+id);
	console.log('display : '+display); _//value of display is incorrect. it return id value_
	return display;
}
render() {
	const data = 'Hi {first_name}, welcome to xxx recruitment agency\'s Messenger bot!';
	const params = [
		{
			id: 'first_name',
			display: 'First Name',
		},
		{
			id: 'last_name',
			display: 'Last Name',
		},
		{
			id: 'full_name',
			display: 'Full Name',
		}
	];
	return (
		<MentionsInput
			className="mention-on-editor"
			value={data}
			onChange={this.onChange}
			style={defaultStyle}
			markup='{__id__}'
			displayTransform={this.displayTransform}
			placeholder={'Mention parameter using \'@\''}
			suggestionsPortalHost={portalEl}
		>
			<Mention data={params} style={defaultMentionStyle}  />
		</MentionsInput>
	);
}
```

**Expected behaviour:**

I'm expecting below:

**display markup**: Hi First name, welcome to xxx recruitment agency's Messenger bot! 
**value**: Hi {first_name}, welcome to xxx recruitment agency's Messenger bot! 

**Observed behaviour:**

displayTransform function return 'display' as 'id' instead. so instead of return 'First Name' that it returns 'first_name' value.

Please advise how can I achieve the above result?

**Comment by jfschwarz** [comment]
`displayTransform` receives as its `id`. `display`, `type` arguments the values extracted from the mentions markup, which in your case (`{__id__}`) only includes a placeholder for the `id`. In this case, react-mentions will set the missing `display` argument to `id` by default.

It is up to you to look up the matching entry from your `params` array in the displayTransform function. react-mentions uses the `<Mention />`'s `data` prop exclusively for rendering suggestions.
