### ISSUE TITLE
Cannot get multiple mentions to work

### ISSUE THREAD

**Issue by iseabock** [signavio/react-mentions#289]
**Steps to reproduce:**
if I type something like this into the textarea:

this is my first mention @user1 and then @user2

I get:

this is my first mention user1 and then @user2

no @ on the first mention

**Expected behaviour:**

the expected output:

this is my first mention @user1 and then @user2

Here is my code:
```
            <MentionsInput
              className="mentionTextarea"
              value={this.props.defaultValue}
              onChange={this.props.onChange}
              markup={'@__display__'}
            >
              <Mention
                trigger="@"
                data={this.props.userNames.map(user => ({
                  id: user.accountId,
                  display: `@${user.key}`
                }))}
              />
            </MentionsInput>

```

I would also mention ideally I would like the following markup to work, since ultimately these will be Jira mentions

```
            <MentionsInput
              className="mentionTextarea"
              value={this.props.defaultValue}
              onChange={this.props.onChange}
              markup={'[~__display__]'}
            >
              <Mention
                trigger="@"
                data={this.props.userNames.map(user => ({
                  id: user.accountId,
                  display: `@${user.key}`
                }))}
              />
            </MentionsInput>
```

**Comment by jfschwarz** [comment]
I cannot really reproduce the problem you are describing using your snippets with the latest version of react-mentions. Also, the second snippet works flawlessly. However, there is obviously some confusion about markup and the display values.

The first snippet generates a markup of the form `@@anAccountId`, one `@` char coming from the markup pattern the second one as part of the inserted `display` value. This markup cannot be detected by our default regexp you will have to provide a custom `regex` prop to support this pattern. My guess is, that you actually just want to have a single `@` character in the markup value which should stay visible also in the highlighted plain text shown to the user.

```
            <MentionsInput
              className="mentionTextarea"
              value={this.props.defaultValue}
              onChange={this.props.onChange}
              markup={'@__id__'}
              displayTransform={(id) => `@${id}`}
            >
              <Mention
                trigger="@"
                data={this.props.userNames.map(user => ({
                  id: user.key
                }))}
              />
            </MentionsInput>
```

Also, the second snippet indicates some confusion around `display` properties. The attributes of the suggestions only define the values to insert at the respective placeholders in the markup. They are not used in any other way. Thus, it does not make sense to define an `id` attribute if the markup only has a placeholder for `__display__`.

Something like this would make more sense:

```
            <MentionsInput
              className="mentionTextarea"
              value={this.props.defaultValue}
              onChange={this.props.onChange}
              markup={'[~@__id__]'}
              displayTransform={(id) => `@${id}`}
            >
              <Mention
                trigger="@"
                data={this.props.userNames.map(user => ({
                  id: user.key
                }))}
              />
            </MentionsInput>
```

**Comment by amitkumar-bst** [comment]
It's not working for multiple mentions. Markup removed for all mentions except last one.
