### ISSUE TITLE
Unable to trigger suggestions if the preceding character is special character. (, ), #, * etc

### ISSUE THREAD

**Issue by gargroh** [signavio/react-mentions#295]
Unable to trigger suggestions if the preceding character is special character. `(`, `)`, `#`, `*` etc

**Steps to reproduce:**

1. Open http://signavio.github.io/react-mentions/
2. Type `(` in any of the textarea
3. Then try to trigger mentions, as in given example use `@`, then suggestions are not able to trigger

**Expected behaviour:**
Suggestions should be visible

**Observed behaviour:**
Suggestions are not visible

**Workaround:**
Unknown

Let me know if this is a bug or in case i am missing something.

**Comment by nmeierpolys** [comment]
I'm running into this as well. It looks like the regex is only set to match at the beginning of the line, or immediately following a whitespace character:
`(?:^|\\s)` in https://github.com/signavio/react-mentions/blob/master/src/MentionsInput.js#L39

Is there a reason to restrict to that context?

**Comment by jfschwarz** [comment]
It is possible to completely customize the regex for extracting mentions from the markup via the `regex` prop. This is not really well documented yet, but you can find an example here: https://github.com/signavio/react-mentions/blob/master/demo/src/examples/Emojis.js#L33
