### ISSUE TITLE
App Failing (React error) on Regex Mismatch

### ISSUE THREAD

**Issue by LaurentRos** [signavio/react-mentions#296]
**Steps to reproduce:**

1. Go to https://codesandbox.io/s/wk36wjxqpw
2. Follow the instructions

**Expected behaviour:**
The app doesn't fail

**Observed behaviour:**
The app fails (React error)

**Workaround:**
Use a heavier markup

**Comment by jfschwarz** [comment]
I've migrated your example to the latest version of react-mentions (v3) and where the problem has been fixed: https://codesandbox.io/s/p36lnwr0kq
