### ISSUE TITLE
Move displayTransform and markup options to <Mention />

### ISSUE THREAD

**Issue by mxstbr** [signavio/react-mentions#300]
I want to add both a mention popover for `@username` as well as a emoji suggestion popover for `:emoji:` to my input. Right now my setup looks like this (see #299 for an explanation of the markup and displayTransform options):

```JSX
    <MentionsInput
      displayTransform={username => `@${username}`}
      markup="@[__id__]"
      {...props}
    >
      <Mention
        trigger="@"
        data={searchUsers}
        appendSpaceOnAdd={true}
        renderSuggestion={renderSuggestion}
      />
    </MentionsInput>
```

Unfortunately, **this makes it impossible to add emoji suggestion as the `displayTransform` and `markup` options need to be different**.

Ideally, I want to be able to set those options per `<Mention />` rather than for the entire input, something like this:

```JSX
    <MentionsInput {...props}>
      <Mention
        trigger="@"
        displayTransform={username => `@${username}`}
        markup="@[__id__]"
        data={searchUsers}
        appendSpaceOnAdd={true}
        renderSuggestion={renderUserSuggestion}
      />
      <Mention
        trigger=":"
        displayTransform={emoji => unicode[emoji]}
        markup=":__id__:"
        data={emojis}
        appendSpaceOnAdd={true}
        renderSuggestion={renderEmojiSuggestion}
      />
    </MentionsInput>
```

Is there a way to work around this?

**Comment by jfschwarz** [comment]
Quick update: We're working on supporting this use case. This will be a breaking change and we have to do some more testing, document the new API and migration path.

**Comment by mxstbr** [comment]
Amazing! :tada: Excited!

**Comment by mxstbr** [comment]
Amazing!!

**Comment by prabhatkashyap902** [comment]
is it released?

**Comment by indjeto** [comment]
It seems so, but not mentioned in the docs.
