### ISSUE TITLE
After Submit react-mention how to show on UI in React

### ISSUE THREAD

**Issue by srjkrl20011991** [signavio/react-mentions#303]
In my application I am adding a comment like '@Suraj.199 Please start working on ZYX task'.
below I have all the comments about that ticket so I want to show "Suraj.199" in link type.

How I store a value in the backend so I know on the front end this work I need to convert in the link.
how we convert in selected name or email in the link?

**Comment by jfschwarz** [comment]
For rendering, you'll have to parse the submitted value which contains markup of some form for all the user mentions and turn it into DOM elements. This is out of the scope of this library.

**Comment by amitava82** [comment]
You should expose the helper function that you use to show the markup text in the textarea. That solves the issue.
