### ISSUE TITLE
Possible to render mention as "markdown" in hidden textarea?

### ISSUE THREAD

**Issue by dep** [signavio/react-mentions#307]
I'm using a pretty standard pattern here:

```
<MentionsInput
  value={this.state.value}
  onChange={this.onChange}
  style={defaultStyle}
  markup="@[__display__](/users/profile/__id__)"
  displayTransform={(display, id) =>
    `@[${id}](/users/profile/${display})`
  }
  {...props}
>
  <Mention
    trigger="@"
    data={users}
    renderSuggestion={(
      suggestion,
      search,
      highlightedDisplay,
      index,
      focused
    ) => (
      <div className={`user ${focused ? 'focused' : ''}`}>
        {highlightedDisplay}
      </div>
    )}
    style={defaultMentionStyle}
  />
</MentionsInput>
```

What I would like is if I could render a nicely styled "Name" to the user (hidden markdown), but underneath, in the hidden `textarea`, have the mention encoded in markdown format.  Is this possible?

**Comment by dep** [comment]
I'm realizing now that the `textarea` isn't actually hidden, but instead lies underneath the `div` which adds the highlighting and such. Makes sense.  However, it would be ideal if I could show the user one presentation, and save an encoded version underneath.

**Comment by jfschwarz** [comment]
I initially tried something similar back when we started developing this component. The problem with this approach is that hiding the textarea effectively takes away the text editing features it offers: the blinking text cursor, text selection/replace, pasting text, etc.

My conclusion was, that if you need rich styling of mentions, just going for a `contenteditable` div is probably a better option.

Why do you need the markup value in an extra textarea? Since we call `onChnage` with that markup value you can just get it from there. You could of course also store it in a wrapping component's state and render a hidden textarea next to `<MentionsInput />` it.

**Comment by dep** [comment]
Thanks @jfschwarz - The hidden `textarea` approach populating with a `value` of `this.state` seems to work really well. Pasting here for reference:

```js
handleChange = e => {
  this.setState({ value: e.target.value });
};

state = {
  value: ''
};

render() {
  const {
    classes,
    className,
    data,
    inputRef,
    mentionInputRef,
    name,
    onChange,
    theme,
    value,
    ...props
  } = this.props;
  return (
    <div className={classes.root}>
      <MentionsInput
        className={classes.input}
        inputRef={mentionInputRef}
        value={this.state.value}
        onMouseUp={this.handleClick}
        onChange={this.handleChange}
        style={defaultStyle}
        {...props}
      >
        <Mention
          trigger="@"
          data={data}
          renderSuggestion={(
            suggestion,
            search,
            highlightedDisplay,
            index,
            focused
          ) => (
            <div className={`user ${focused ? 'focused' : ''}`}>
              {highlightedDisplay}
            </div>
          )}
          style={defaultMentionStyle}
        />
      </MentionsInput>
      <textarea
        className={classes.hiddenTextarea}
        id={name}
        name={name}
        ref={inputRef}
        value={this.state.value}
        readOnly
      />
    </div>
  )
}
```
