### ISSUE TITLE
Mention highlights can get misplaced in large scrolllable containers

### ISSUE THREAD

**Issue by joelwatson** [signavio/react-mentions#310]
**Steps to reproduce:**

1. In the "Scrollable Container" example, enter the following text:

```
Bacon ipsum dolor amet t-bone pork belly pork loin turkey jerky chuck ham hock beef ribs alcatra porchetta kevin. Meatloaf drumstick chicken corned beef t-bone ham hock alcatra bresaola sausage. Jowl strip steak drumstick turkey. Tongue shankle pork swine salami tri-tip sausage chuck. Chicken turkey pancetta biltong. Strip steak fatback kevin jowl sirloin filet mignon beef andouille salami boudin ribeye.

Pork cow brisket, sausage frankfurter meatball corned beef capicola tri-tip spare ribs boudin ribeye. Fatback chuck burgdoggen meatloaf ribeye tail sirloin doner. T-bone short ribs landjaeger spare ribs drumstick cupim, ham hock shankle alcatra chicken rump turkey salami. Jerky salami buffalo ball tip picanha meatball drumstick rump.
```
https://signavio.github.io/react-mentions/master/

2. In the second paragraph, remove `ham hock` and replace with a `mention`

**Expected behaviour:**
Mentioned user should be highlighted correctly

**Observed behaviour:**
Highlight background color is horizontally misaligned
![image](https://user-images.githubusercontent.com/9660362/53294394-70a04e00-37ab-11e9-9179-994312090548.png)

**Workaround:**
N/A

**Comment by dep** [comment]
@joelwatson 
I was able to get around this with some extra css, hope this helps:

```jss
const MAX_HEIGHT = '16rem';

const defaultStyle = {
  control: {
    maxHeight: MAX_HEIGHT,
    overflowY: 'auto'
  },
  highlighter: {
    paddingTop: PADDING.paddingTop,
    left: '.15rem',
    paddingRight: '1rem',
    boxSizing: 'content-box',
    maxHeight: MAX_HEIGHT,
    width: '110%',
    overflow: 'auto'
  }
};
```

**Comment by zenVentzi** [comment]
In case somebody gets here, using **css reset**, it could be causing the issue.

**Comment by lanekatris** [comment]
We use [Semantic](https://react.semantic-ui.com/) and it was applying `line-height` to my `textarea` and not the highlight `div`. Once I added `line-height` to the highlight `div`, which "matched" with the `textarea`; it fixed the issue.

**Comment by jfschwarz** [comment]
closing this, as the problem seems to stem from inconsistent styling of the `control` and `highlighter` elements.
