### ISSUE TITLE
user mentions highlight to be colored text instead of colored background?

### ISSUE THREAD

**Issue by srjkrl20011991** [signavio/react-mentions#311]
**Steps to reproduce:**

1.  add color instead of background color 
2. it looks like textbox color mixed with mentions clor
3.  Find image
4. any latest propery ?
5. paste hack code if any

**Expected behaviour:**
the only colour need to show in textbox
**Observed behaviour:**
i tried hack of z-index and contenteditable but 
a pointer always behaves on textarea and it causes unexpected behaviour
**Workaround:**
![32728508-ac686376-c891-11e7-8fc3-b9a8123d7dfe](https://user-images.githubusercontent.com/31344825/53321216-c5ec7480-38fd-11e9-8cfd-bdc3f1a2ce2f.png)

Kindly help @jfschwarz

**Comment by jfschwarz** [comment]
You have to make sure that the textarea and the highlighting div have identic style definitions. In your screenshot, it appears that the blue text of the highlighting div uses a different font family or size. Once the characters in the two layers really overlap, you might further improve the result by adding a white background to the mention styles. 

Let's keep further discussion about this topic at #184.
