### ISSUE TITLE
Clearing value with an inputRef results in a highlighter pointing to non-existent text

### ISSUE THREAD

**Issue by dep** [signavio/react-mentions#312]
**Steps to reproduce:**

1. Create a mention with an inputRef
2. Compose a Mention
3. Clear the input dynamically
4. The text disappears but the 'highlight' remains

**Expected behaviour:**

1. Highlight clears with text

**Screenshots:**

Before clearing:
![](http://dl.dpeck.net/q34nHK+)

After clearing:
![](http://dl.dpeck.net/oCEnnU+)

Any workarounds appreciated.

**Comment by jfschwarz** [comment]
Instead of clearing the value attribute of the input you should clear the state that you pass as the `value` prop to the `<MentionsInput />`

**Comment by dep** [comment]
@jfschwarz This sounds like a good approach but would you be so kind as to elaborate? I realize this is perhaps out of scope of the library, so any help is appreciated.

**Comment by jfschwarz** [comment]
You should generally refrain from imperative DOM updates when working with React. The React component can only reliably work if it can assume full control over its DOM elements.

react-mentions is designed to be used as a [controlled component](https://reactjs.org/docs/forms.html#controlled-components). In general, I'd advise to just read the official React Docs, which are truly excellent and should help you to understand the idea of one-way data flow and component composition.
