### ISSUE TITLE
MentionsInput - support for passing in className as prop?

### ISSUE THREAD

**Issue by rmincling** [signavio/react-mentions#313]
**Steps to reproduce:**

1. Tried adding passing className prop to MentionsInput component.

**Expected behaviour:**
The internal input to have the classes applied to it.
**Observed behaviour:**
Classes not applied to input
**Workaround:**
Add support for className to MentionsInput

Extra notes:
When I passed the class string as a 'class' prop, the classes are applied to the internal input, but obviously this is not the way to go.

**Comment by jfschwarz** [comment]
Well, we apply the `className` to the outermost container `div`, while the input receives a derived className by appending the `__input` suffix. If you want to customize this, you can pass `classNames` mapping prop:

```
<MentionsInput
        className="m"
        classNames={{
          m__input: 'foo',
        }}
      >
```

More info here: https://github.com/jfschwarz/substyle

**Comment by rmincling** [comment]
Thank you so much, I wasn't aware of this! Cheers!

**Comment by doublejosh** [comment]
The classNames prop does not seem to take a value for `mentions__suggestions__item--focused`
