### ISSUE TITLE
Question: is there a way to customize the <Mention display

### ISSUE THREAD

**Issue by pete0877** [signavio/react-mentions#322]
Hi, I see that  the `<Mention` tag supports `style` property but I was hoping to use custom style based on the data item being mentioned.  E.g. imagine if I wanted to use different background color for the @ users based on something I find in their `display` value. 

I am already successfully doing this for the suggestions drop-down using `renderSuggestion`. 
I tried to mess around with the `displayTransform` but without much success. It appears to be meant to return text and not markup. Perhaps I have given up too quickly though. 

I know I could have two different `<Mention` tags with different data sets and styes but they would have to respond to different triggers and I want just one trigger of `@`.

If there is a place where you think I could add this code, I'm happy to create a fork and later PR it. 

Thank you!

**Comment by jfschwarz** [comment]
You can also have two different `<Mention>` tags for the same trigger of `@`. What needs to be different is their markup pattern, so react-mentions can tell from the markup in the `value` prop, which kind of mention it deals with.

For example the following would work:

```
<MentionsInput value={value} onChange={onChange}>
        <Mention
          markup="@[__display__](type1:__id__)"
          trigger="@"
          data={data1}
          style={{ backgroundColor: '#cee4e5' }}
        />
        <Mention
          markup="@[__display__](type2:__id__)"
          trigger="@"
          data={data2}
          style={{ backgroundColor: '#d1c4e9' }}
        />
</MentionsInput>
```

**Comment by pete0877** [comment]
Brilliant - thank you! Great little component.

**Comment by Al-aminAzad** [comment]
Hey, I am facing a problem. i am getting value in onChange event like @[user_name](id). But i only want like @[username] or @username. not id within parentheses. @jfschwarz any suggestions.

**Comment by wangsy503** [comment]
> displayTransform

If you are facing the problem that only `id` shows up after `displayTransform`, you can try this:
```javascript
displayTransform={(id, display) => "@" + (display)}
```

**Comment by chiruvanapalli** [comment]
how to insert image along with text in textarea not only in suggestions? I have an issue in suggestions getting but after selected not getting avatar image

import React, { useState } from 'react';
import { MentionsInput, Mention } from 'react-mentions';
import defaultMentionStyle from './defaultMentionStyle';
import defaultStyle from './defaultStyle';
import SCLogo from './assets/sellerscommerce.svg';

const users = [
  {
    id: 'jack',
    display: 'Jack',
  },
  {
    id: 'john',
    display: 'john',
  },
];

const users2 = [
  {
    id: 'jack1',
    display: '2Jack',
    image: <img src={SCLogo} alt="User" />,
    type: 'user',
  },
  {
    id: 'john2',
    display: '2john',
    image: <img src={SCLogo} alt="Role" />,
    type: 'role',
  },
];

const Mentions = () => {
  const [value, setValue] = useState('');
  const [suggestions, setSuggestions] = useState([]);

  const onChange = (e, newValue, newPlainTextValue, mentions) => {
    setValue(newValue);
    // You can handle the suggestions here if needed
    setSuggestions(mentions);
  };

  const renderSuggestion = (suggestion, search, highlightedDisplay) => (
    <div>
      {suggestion.image}
      {highlightedDisplay}
    </div>
  );

  return (
    <div>
      <img src={SCLogo} alt="Logo" />
      <MentionsInput
        value={value}
        onChange={onChange}
        style={defaultMentionStyle}
        placeholder="Type @ or # to mention"
      >
        <Mention
          markup="@{{__id__||__display__||image||__type__}}"
          trigger="@"
          data={users}
          style={{ backgroundColor: '#cee4e5' }}
          renderSuggestion={renderSuggestion}
        />
        <Mention
          markup="#{{__id__||__display__||image||__type__}}"
          trigger="#"
          data={users2}
          style={{ backgroundColor: '#fff' }}
          renderSuggestion={renderSuggestion}
        />
      </MentionsInput>
    </div>
  );
};

export default Mentions;
