### ISSUE TITLE
Help with (likely) an obvious question

### ISSUE THREAD

**Issue by edPratt** [signavio/react-mentions#323]
Everything is working as expected, but I want to save to state something like @username instead of the structure that is imposed by the markup string, but for the life of me I can't figure it out. Anyone?

**_Example_**: 
_Instead of ..._
![image](https://user-images.githubusercontent.com/6599975/56780188-559e8a00-67ac-11e9-8921-65d037a2dc82.png)
_I'd rather have ..._
![image](https://user-images.githubusercontent.com/6599975/56780253-90a0bd80-67ac-11e9-8d2f-f8d69637385a.png)

![image](https://user-images.githubusercontent.com/6599975/56780087-ede83f00-67ab-11e9-8a01-5a3e7bb2304b.png)

![image](https://user-images.githubusercontent.com/6599975/56780140-1ec87400-67ac-11e9-8097-68803f1c3ba4.png)

**Comment by jfschwarz** [comment]
It is possible in the latest version (v3):

```
<MentionsInput>
        <Mention
          trigger="@"
          displayTransform={id => `@${id}`}
          markup="@__id__"
          data={users}
          regex={/@(\S+)/}
          appendSpaceOnAdd
        />
        <Mention
          trigger="#"
          displayTransform={id => `@${id}`}
          markup="#__id__"
          data={labels}
          regex={/#(\S+)/}
          appendSpaceOnAdd
        />
      </MentionsInput>
```

**Comment by edPratt** [comment]
Ok, so I tried fitting that into my application, but there are errors. It properly displays the mentions in a dropdown, but once I click on one I get the same errors as before. 

![image](https://user-images.githubusercontent.com/6599975/56812814-a7293200-6809-11e9-9160-9b0ff8964c69.png)

![image](https://user-images.githubusercontent.com/6599975/56812832-b0b29a00-6809-11e9-9f1f-9b364f54765f.png)

**Comment by jfschwarz** [comment]
Note that my code snippet is based on react-mentions version 3 (see breaking changes here: https://github.com/signavio/react-mentions/releases/tag/v3.0.0). Your code still passes the `type` prop to `<Mention>` which is not needed and not supported any longer.

Also, the first error seems to originate from your code and not from react-mentions.

**Comment by edPratt** [comment]
Ok, thanks for your help!
