### ISSUE TITLE
Customising mark-up variable names?

### ISSUE THREAD

**Issue by rmincling** [signavio/react-mentions#324]
Hi,

I was just wondering if it is currently possible to customise/define what fields to extract in the markup property? Currently the fields are 'id' and 'display'. Is there any way this can be changed to something like `@[__username__](__pk__)` ?

Kind regards,

Rob

**Comment by jfschwarz** [comment]
There is no point in changing the name of the placeholders. We have to define some API and these are the placeholder names (& suggestion attributes) we chose. It shouldn't be a problem to map your domain objects to our API and back.

**Comment by rmincling** [comment]
Yes, fair point, was worth asking. Thank you  for the quick response.
