### ISSUE TITLE
Warning: React does not recognize the `allowSpaceInQuery` prop on a DOM element.

### ISSUE THREAD

**Issue by delgermurun** [signavio/react-mentions#325]
Hello,

I get this warning on `react-mentions v3.0.0` and `React v16.8.6`. Do you see it?

![image](https://user-images.githubusercontent.com/492616/57351837-e8b8c600-7195-11e9-9153-ccf213e0e405.png)

**Comment by nhunsaker** [comment]
Any custom attributes you're using need to be removed from the text area.
https://github.com/signavio/react-mentions/blob/master/src/MentionsInput.js#L186
```
  renderTextarea = props => {
    let cleanProps = { ...props };
    ['allowSpaceInQuery', 'displayTransform'].forEach(prop => {
      delete cleanProps[prop];
    });
    return <textarea ref={this.setInputRef} {...cleanProps} />
  }
```

**Comment by gregoryjjb** [comment]
I believe adding `allowSpaceInQuery` to the propTypes of MentionsInput would fix this, as the keys of propTypes are stripped out here https://github.com/signavio/react-mentions/blob/master/src/MentionsInput.js#L146.

**Comment by blacelle** [comment]
Shouldn't `displayTransform` also be added in propTypes?

We have:

```
Warning: React does not recognize the `displayTransform` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `displaytransform` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    in textarea (created by MentionsInput)
```

**Comment by EdwinKato** [comment]
> Shouldn't displayTransform also be added in propTypes?

In case someone else lands on this, `displayTransform` should be on the `Mention` component. That way, you won't see any warnings for it
