### ISSUE TITLE
Unable to style spinner and inner divs of LoadingIndicator component

### ISSUE THREAD

**Issue by koshkarik** [signavio/react-mentions#327]
**Steps to reproduce:**

1. Add isLoading prop to Mention component
2. Style with css suggestions -> loadingIndicator -> spinner
3. Styles are not applied to spinner div and to 3 child divs (only to LoadingIndicator)

**Expected behaviour:**
Ability to style loading spinner with css

**Observed behaviour:**
Styles are not applied. Here is example https://codesandbox.io/s/simple-reactmentions-test-q1xrr.
I think problem is here https://github.com/signavio/react-mentions/blob/master/src/SuggestionsOverlay.js#L125
If i change this line to `<LoadingIndicator style={this.props.style('loadingIndicator') }/>` everything works as expected

**Comment by jfschwarz** [comment]
Thank you for reporting this bug and for even spotting the cause of it :) Do you mind submitting a PR with the change of this line as proposed? ;)

**Comment by koshkarik** [comment]
PR created ;)
