### ISSUE TITLE
fireEvent.change with RTL + jest (jsdom) doesn't fire change event

### ISSUE THREAD

**Issue by mcMickJuice** [signavio/react-mentions#330]
I'm trying to test this component with React Testing Library using Jest and Jsdom.  When I simulate a change event on this component, the `onChange` event doesn't fire.

Here's a sandbox that reproduces this issue - https://codesandbox.io/s/festive-bird-5i8l4

I believe the source of the issue is [here](https://github.com/signavio/react-mentions/blob/master/src/MentionsInput.js#L290).  I believe in jsdom `if (currentDocument.activeElement !== ev.target)` is resulting in true. I've confirmed this by throwing an error from that block when running these tests.

**Steps to reproduce:**

1. write a test with React Testing Library's fireEvent.change
2. call `change` and pass in element pertaining to MentionInput
3. notice that the onChange event passed into MentionInput is never called

**Expected behaviour:**
I would expect `onChange` to fire when I try to simulate a change event with react-testing-library

**Observed behaviour:**
`onChange` is not fired when I try to simulate a change event with react-testing-library

**Workaround:**
Not use RTL?

**Comment by frontendphil** [comment]
Hey @mcMickJuice does this work if you simulate a `focus` event on the input first?

**Comment by mcMickJuice** [comment]
It does not:

```
it('change event should call passed in onChange', () => {
    const mock = jest.fn()
    const { getAllByTestId } = render(<Mentions value="" onChange={mock} />)

    const elem = getAllByTestId('mentions')[0]

    fireEvent.focus(elem)

    fireEvent.change(elem, {
      target: {
        value: 'foo'
      }
    })

    expect(mock).toHaveBeenCalled()
  })
```

Updated the codesandbox link above to include that check

**Comment by mcMickJuice** [comment]
Worth mentioning that commenting out the IE check (https://github.com/signavio/react-mentions/blob/master/src/MentionsInput.js#L290) results on `MentionInput`s  `onChange` to fire but with newValue as empty string.

**Comment by tbertrand7** [comment]
I am currently running into this issue myself. Was this issue ever resolved or was a workaround found?

**Comment by tbertrand7** [comment]
I managed to figure out a workaround to this issue. The problem was the textarea must be focused and have the select set to the 0 position before calling `fireEvent.change()`:

``` TS
const setMentionsInputValue = (wrapper: HTMLTextAreaElement, value: string) => {
  wrapper.focus();
  fireEvent.select(wrapper, {
    target: { selectionStart: 0, selectionEnd: 0 },
  });
  fireEvent.change(wrapper, {
    target: {
      value: value,
      selectionStart: value.length,
      selectionEnd: value.length,
    },
  });
};
```

**Comment by giancarlo88** [comment]
I'm having the same issue with Enzyme: 

```js
wrapper.find('MentionsInput').simulate('change', {
  target: {
    value: 'foo'
   }
});
```
The above won't trigger a change. What I can do as a workaround is: 

```js
inputContainer
  .find('MentionsInput')
  .props()
  .onChange({ target: { value: input } });
```
But I'd rather simulate the event as this is relies on the `onChange` implementation. 

Any suggestions? I've tried adding the  `select` event and the `selectionStart`/`selectionEnd` properties but didn't seem to have any luck.

**Comment by ilantuqqi** [comment]
> I managed to figure out a workaround to this issue. The problem was the textarea must be focused and have the select set to the 0 position before calling `fireEvent.change()`:
> 
> ```ts
> const setMentionsInputValue = (wrapper: HTMLTextAreaElement, value: string) => {
>   wrapper.focus();
>   fireEvent.select(wrapper, {
>     target: { selectionStart: 0, selectionEnd: 0 },
>   });
>   fireEvent.change(wrapper, {
>     target: {
>       value: value,
>       selectionStart: value.length,
>       selectionEnd: value.length,
>     },
>   });
> };
> ```

God bless you my friend!

**Comment by almeidarruben** [comment]
@ilantuqqi your solution works to trigger the `change` event but if you check the DOM continues unchanged.

And this is because the initial value is set through the `value` prop it should be set on the `defaultValue` instead.

If you try this, the test will pass:
```javascript
const { getByTestId} = render(<textarea data-testid="my-test-input" defaultValue="First value" />);
const inputField = getByTestId('my-test-input');
fireEvent.change(inputField, {target: {value: 'New value'}});
expect(inputField.value).toBe('New value');
```

If you change to `value`, will fail:
```javascript
const { getByTestId} = render(<textarea data-testid="my-test-input" defaultValue="First value" />);
```

**Comment by jaxxreal** [comment]
I'd suggest to putting @tbertrand7 (thanks man!) comment to documentations. I spent few days poking around until I found the solution.
