### ISSUE TITLE
Add the possibility to mention users with accents without having to search with the accents

### ISSUE THREAD

**Issue by ybri** [signavio/react-mentions#360]
**Steps to reproduce:**

1. Mention 'Jésse'
2. See that 'Jesse Pinkman' is not proposed

**Expected behaviour:**

I want to be able to search for a user to mention ignoring the accents.
When I search for 'eric', I would like to find 'éric' if the ignore accent prop is set to true.

**Observed behaviour:**

When I search for 'eric', the names containing 'éric' are not showing and there is no easy way of overriding this behaviour from outside the library.

**Workaround:**

I created the PR [#359 ](https://github.com/signavio/react-mentions/pull/359) where I added the prop ignoreAccents to MentionInput, SuggestionOverlay and Suggestion and created a service to get a substring index ignoring the accents or not.

**Comment by jfschwarz** [comment]
closed with #359

**Comment by Floriferous** [comment]
It seams like this is still an issue in some cases. If you want to mention `Élise`, you can do it with `élise`, but not `elise`.

**Comment by yannbriancon** [comment]
Hello @Floriferous,

If you want to ignore the accents, you need to add the prop `ignoreAccents` to the `MentionsInput`.
By the way, I see that it is not in the README.
