### ISSUE TITLE
the mention color not obvious

### ISSUE THREAD

**Issue by Yussur90** [signavio/react-mentions#368]
**Steps to reproduce:**

 the mention color not good and not obvios even when i put text sahdow

**Expected behaviour:**
send prop color

**Observed behaviour:**

**Workaround:**

**Comment by frontendphil** [comment]
Hey @Yussur90! Can you elaborate a bit more on the issue you're facing? If it's about styling this section of the readme might help you: https://github.com/signavio/react-mentions#styling

TL;DR you can add styles to each `Mention` component to manipulate for instance the background color which is used. Does that help with your issue?

**Comment by Yussur90** [comment]
<img width="1200" alt="Screen Shot 2019-11-12 at 3 04 03 PM" src="https://user-images.githubusercontent.com/36266815/68674098-ddd45900-055d-11ea-8b76-24ba6bf0c08a.png">

**Comment by Yussur90** [comment]
position: relative;
  z-index: 1;
  color: #4e7bd6;
  text-shadow: 2px 1px 0px white, 0px 0px 0px white, -1px 1px 0px white,
    -1px -1px 0px white;

  pointer-events: none;

**Comment by Yussur90** [comment]
i use text-shadow for change the color which is not very obvious

**Comment by Yussur90** [comment]
@frontendphil

**Comment by frontendphil** [comment]
Hey, @Yussur90 I don't see a question in your last comments. This makes it rather hard for me to give you further advice.

**Comment by Yussur90** [comment]
there is no attribute for changing color no props for changing mention color that is the problem 
i can change it only with this style  but it is not obvious as you see in pictue that i put!!!!
position: relative;
z-index: 1;
color: #4e7bd6;
text-shadow: 2px 1px 0px white, 0px 0px 0px white, -1px 1px 0px white,
-1px -1px 0px white;

pointer-events: none;

**Comment by frontendphil** [comment]
Ok, now I get it :) You're correct that there is no such prop. This component uses a standard `textarea` or `input`. Since you cannot define the color for individual words in these components this is also not possible for mentions. That's why you can essentially only change what is **behind** the mention. You could give it a background, draw a border, add a drop shadow. But nothing to the text itself I'm afraid.

**Comment by frontendphil** [comment]
However, nice trick you've found there :D

**Comment by Yussur90** [comment]
ok thank you :D

**Comment by gabrielmicko** [comment]
@Yussur90 you are amazing for coming up with this text-shadow trick. It is a good workaround as background-color approach kills `::selection`.
