### ISSUE TITLE
Copy/paste sets cursor position to end of textarea

### ISSUE THREAD

**Issue by EliottGaboreau** [signavio/react-mentions#375]
**Steps to reproduce:**

This bug has been observed in the examples provided at https://react-mentions.wolf-pack.now.sh/

1. Use a mentions textarea with `EXPERIMENTAL__cutCopyPaste` set to true. 
2. Copy some text (from anywhere, not necessarily from a react-mentions textarea)
3. Paste on the textarea

**Expected behaviour:**

Cursor is positionned right after the text that was just pasted

**Observed behaviour:**

Cursor is positioned at the end of the textarea

**Comment by kishan143-jaiswal** [comment]
facing same issue whole copy pasting the paragaph its cursor position is showing after some space

**Comment by Ethorsen** [comment]
Any fix/workaround for this issue yet?

**Comment by krishanmarco** [comment]
I can confirm this issue exists with a 100% reducibility rate. Is there any plan to look into it?
A fast way to reproduce it is by disabling the `onChange` callback, selecting the text input with already pre-inserted text and pressing any key (The cursor will jump to the end).
  
I can also confirm that it's part of `EXPERIMENTAL_cutCopyPaste` as removing that seems to solve the issue.

A timeline for this issue would be great 🥇

**Comment by lucasMarioza** [comment]
Is there any fix or workaround for that?

**Comment by robbinjanssen** [comment]
I've created a pull request to fix this issue. You can check it out at https://react-mentions-git-fork-robbinjanssen-rja-fix-p-cb6cd8-signavio.vercel.app/
