### ISSUE TITLE
Additional onChange event information

### ISSUE THREAD

**Issue by r-inaldi** [signavio/react-mentions#385]
I've noticed that for change events the library mocks a new event object that contains only the value of the target. 

https://github.com/signavio/react-mentions/blob/master/src/MentionsInput.js#L519

On my application, I rely a lot on the `id` and `name` of form elements, would be of interest to add them as well to the target?

**Steps to reproduce:**

1. Register an `onChange` listener to `MentionsInput`;
2. Inspect the event after triggering changes.

**Expected behaviour:**

Have the `id` and `name` of the input that the event was triggered on to reflect the HTML events API.

**Observed behaviour:**

Neither `id` nor `name` are present.

**Workaround:**

Had to do this inside the change listener:

```js
const handleChange = useCallback(
    event => {
      /* eslint-disable no-param-reassign */
      event.target.id = id;
      event.target.name = name;
      if (onChange) onChange(event);
      /* eslint-enable no-param-reassign */
    },
    [id, name, onChange],
);
```

**Comment by jfschwarz** [comment]
I'd suggest doing this in a wrapping component in your codebase. In the future, we'd rather get rid of the event mock structure and simply propagate the string value directly.
