### ISSUE TITLE
Custom jsx inside MentionsInput

### ISSUE THREAD

**Issue by PJijin** [signavio/react-mentions#398]
I am trying to insert an image via value MentionsInput. Its accepting string only. Is there any way to insert custom jsx in the message part?  

```
<MentionsInput
					inputRef={inputRef}
					value={<><img src="/test.png" /></>}
					onChange={(e) => setMessage(e.target.value)} 
					style={MentionInputNewStyle}
				>
					<Mention trigger="@" data={users} style={MentionStyle} /> 
				</MentionsInput>
```

**Comment by jfschwarz** [comment]
Accepting custom JSX would not make sense for this component, which is meant to offer a plain textarea with mentioning capabilities rather than a rich-text editor. For rich text editing in React look as Draft.js, Slate.js, react-quill, or other libraries.
