### ISSUE TITLE
Multiline text with mention scrolling not works

### ISSUE THREAD

**Issue by rb162215** [signavio/react-mentions#399]
Mention works perfect for small text, once your text is 4-5 line long with user mention tag in that text and try to scroll mention tag fixed at top of box and other contain scroll

Screenshot attached - 
![Screen Shot 2020-05-21 at 2 55 32 PM](https://user-images.githubusercontent.com/46552717/82544913-797cfc80-9b73-11ea-8fc6-ba9c00e63bf2.png)
![Screen Shot 2020-05-21 at 2 54 42 PM](https://user-images.githubusercontent.com/46552717/82544923-7d108380-9b73-11ea-912c-0f1afe9fa539.png)

Here is my code - 

                        `  
                      <div className="editor-container">
                          <MentionsInput
                                value={this.state.value}
                                onChange={this.handleChange}
                                style={{ fontSize: 16 }}
                                markup={MyCustomeMarker}
                                placeholder="Write here!"
                                className="mentions"
                                allowSuggestionsAboveCursor={true}
                            >
                                <Mention
                                    type="user"
                                    trigger="@"
                                    appendSpaceOnAdd={true}
                                    data={this.renderUserSuggestion}
                                    className="mentions__mention"
                                />
                            </MentionsInput>
                       </div>
                        `

css - 

` 
                  .editor-container{
                  display: block;
                  overflow-y: auto;
        width: 100%;
        height: 250px;
        padding: 50px 30px;
        .mentions__control{
            textarea{
                border: 0px;
                line-height: 1.5;
                padding: 0px;
                color: #000000;
            }
            textarea::placeholder {
                color: #999999;
                font-size: 26px;
                
            }
        }
    }
`
is there any suggestion for this?

**Comment by jfschwarz** [comment]
You need to set `overflow-y: auto` on the `input` element for the scroll sync to work. See example https://github.com/signavio/react-mentions/blob/master/demo/src/examples/Scrollable.js

**Comment by rb162215** [comment]
> You need to set `overflow-y: auto` on the `input` element for the scroll sync to work. See example https://github.com/signavio/react-mentions/blob/master/demo/src/examples/Scrollable.js

Tried this but still not work, after i enter long text then scroll is not working.
See attached screenshot - 
![Screen Shot 2020-05-22 at 3 19 53 PM](https://user-images.githubusercontent.com/46552717/82655390-badade00-9c3f-11ea-9cc3-6b42a7b9e0d1.png)


here you can see scrollbar is at top but still some 5 lines are hide above.
