### ISSUE TITLE
Stop event propagation from MentionsInput?

### ISSUE THREAD

**Issue by onoufriosm** [signavio/react-mentions#444]
From MentionsInput.js (lines 555-557)
```
if (Object.values(KEY).indexOf(ev.keyCode) >= 0) {
  ev.preventDefault()
}
```
On `keyDown` if a relevant Key is pressed while suggestions are shown, the `preventDefault` method is called for the event (rightly so because it will be handled by the MentionsInput component).

However, shouldn't we call `ev.stopPropagation()` as well?

This is causing issues in my use case; when I detect an Enter I want to submit the form. However I don't want to submit the form when suggestions are showing because Enter should select the focused suggestion. `ev.stopPropagation()` would fix this.

I can open a PR to add this but wanted to get the community's opinion before I do that.

**Comment by exception** [comment]
I'm having a similar issue, where my parent div has an onClick function to redirect, but clicking within a Suggestion also causes the propagation, would be nice to just stop propagation on most use cases directly.

**Comment by Skov94** [comment]
I have the exact same issue - I also wish to submit the form on Enter. @onoufriosm do you have any idea when the linked PR will be reviewed and merged? :)

**Comment by onoufriosm** [comment]
Not really. I've just tagged jfschwarz on the PR and waiting. I'm using a forked version for now.
