### ISSUE TITLE
Using nested data not working

### ISSUE THREAD

**Issue by steve-cahn** [signavio/react-mentions#460]
How can I use a nested array as a the data?

Sample Data:

```javascript
const nestedData = [
	{
		id: 'someId',
		data: [
			{
				id: 'cool',
				display: 'Cool you',
			},
			{
				id: 'Brohh',
				display: 'Broo ma man',
			}
		]
	},
	{
		id: 'anotherONe',
		data: [
			{
				id: 'Yarrrr',
				display: 'This is a yaarrrr',
			}
		]
	},
];
```

**Comment by jfschwarz** [comment]
You'll have to transform the results into a flat array first. You can then make use of the custom `renderSuggestion` function to render the items however you like, taking their nesting level into account.
