### ISSUE TITLE
Slows down when having lots of data

### ISSUE THREAD

**Issue by steve-cahn** [signavio/react-mentions#461]
I have a lot of results in the data. like thousands. How can I either virtualize it, or have the plugin kick in only after adding the first or second letter after the trigger?

**Comment by jfschwarz** [comment]
You can provide your own `function (search, callback)` for the `data` prop. This way you have full control on when requests are dispatched (e.g. only when `search.length > 2`) and how results are filtered (e.g., take only the first 20 hits).

We currently don't support virtualized rendering of suggestions.
