### ISSUE TITLE
Testing - getByTestId can't seem to find text-area

### ISSUE THREAD

**Issue by g-monroe** [signavio/react-mentions#481]
I'm trying to write some tests using react-mentions 4.1.1 with testing libraries below:
`"@testing-library/jest-dom": "^5.1.1",
    "@testing-library/react": "^10.0.1",
    "@testing-library/react-hooks": "^3.2.1",
    "@testing-library/user-event": "^12.1.8",`

I was wondering if anyone had the same issue as me or if someone could help point me in the right direction on why this is happening my code and out put is below:

**Test Code:**
```
const { getByTestId } = render(
      <MentionsInput
        value={
          'this is a tagged messaged for @[@test user](12345)'
        }
        onChange={onChange}
        data-testid={'mention_input'}
      >
        <Mention trigger="@" data={data} />
      </MentionsInput>,
    );
    const mentionInput = getByTestId('mention_input');
    await waitFor(() => expect(mentionInput).toBeInTheDocument());
  });

```
**Output:** 
`TypeError: expect(...).toBeInTheDocument is not a function
    
    <html>
      <head />
      <body>
        <div>
          <div
            style="position: relative; overflow-y: visible;"
          >
            <div>
              <div
                style="position: relative; box-sizing: border-box; width: 100%; color: transparent; overflow: hidden; white-space: pre-wrap; word-wrap: break-word; border: 1px solid transparent; text-align: start;"
              >
                <span
                  style="visibility: hidden;"
                >
                  this is a tagged messaged for 
                </span>
                <strong
                  style="font-weight: inherit;"
                >
                  @test user
                </strong>
                 
              </div>
              <textarea
                data-testid="mention_input"
                style="display: block; width: 100%; position: absolute; margin: 0px; top: 0px; left: 0px; box-sizing: border-box; background-color: transparent; font-family: inherit; letter-spacing: inherit; height: 100%; bottom: 0px; overflow: hidden; resize: none;"
              >
                this is a tagged messaged for @test user
              </textarea>
            </div>
          </div>
        </div>
      </body>
    </html>

      59 |     );
      60 |     const mentionInput = getByTestId('mention_input');
    > 61 |     await waitFor(() => expect(mentionInput).toBeInTheDocument());
      62 |   });
      63 | });
      64 |`

Let me know what you guys think. Thank you!

**Comment by mudrila** [comment]
Hey, the error you're getting doesn't seem to be related to `react-mentions`. It says 
`TypeError: expect(...).toBeInTheDocument is not a function`, i.e. your `jest` setup don't know about `toBeInTheDocument` on `expect`. Most likely you haven't added `import "@testing-library/jest-dom";` into your tests setup script
