### ISSUE TITLE
Highlight selection if typed manually instead of selecting from the list

### ISSUE THREAD

**Issue by nikhil2kumar** [signavio/react-mentions#491]
**Steps to reproduce:**

1.  Use the trigger and start typing to see the filtered results
2.  Instead of selecting from the options type it manually

**Expected behaviour:**

The manually typed option should be highlighted in the same manner as the one selected from the options.

**Observed behaviour:**

The correctly typed option should act the same as the selected ones from the option. On selecting from the option, the selection gets highlighted but if the same option is manually typed then it's treated as plain text

I couldn't find a workaround for it. But we can not restrict the user from typing if they don't wanna select from the options. 
Pls, note that they can type the exact option from the list displayed.

**Comment by chenkuangkuang** [comment]
same question !!!

**Comment by chenkuangkuang** [comment]
Anybody find a solution?

**Comment by chenkuangkuang** [comment]
I know how to resolve this ... just use reg to replace text by markup  . maybe readme.md should add this
