### ISSUE TITLE
Invalid hook call when used in a class component

### ISSUE THREAD

**Issue by vsobotka** [signavio/react-mentions#536]
**Steps to reproduce:**

1. Have a version v4 of react-mentions
2. Use the MentionsInput in a class component

**Expected behaviour:**
It works.

**Observed behaviour:**
I get the invalid hook error, together with a stacktrace pointing to the line where MentionsInput is used.
<img width="648" alt="Screenshot 2021-12-23 at 9 49 51" src="https://user-images.githubusercontent.com/4008662/147214254-709fd1a2-0092-40bd-9b49-28792bc0b62b.png">
<img width="526" alt="Screenshot 2021-12-23 at 9 50 49" src="https://user-images.githubusercontent.com/4008662/147214395-b32d82d7-1b3a-4d5a-8497-1eeea712d6b6.png">
<img width="594" alt="Screenshot 2021-12-23 at 9 51 21" src="https://user-images.githubusercontent.com/4008662/147214472-8b87bafc-e70f-454b-8126-dc8ef62c8f35.png">

**Workaround:**
Downgrade the react-mentions to 3.3.2

**Comment by ThibautMarechal** [comment]
Hi @vsobotka Can you try to make a repository with a  minimal reproduction that demonstrates your problem ?
I cannot reproduce your issue (https://codesandbox.io/s/intelligent-franklin-o8o7x?file=/src/App.js)

**Comment by vsobotka** [comment]
Ok so we had a mismatch in the project.
```
"react-dom": "16.3.2",
"react": "16.10.0",
```
but because we do not use hooks and this component uses hooks from v4, we did not discover this problem before.

Setting both to 16.10.0 solved the problem. Sorry for wasting your time.
