### ISSUE TITLE
Cannot install. Getting 404 error

### ISSUE THREAD

**Issue by hesperanca** [signavio/react-mentions#583]
**Steps to reproduce:**

1. run 'npm install react-mentions'

**Expected behaviour:**
Package should install without errors.

**Observed behaviour:**
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/react-mentions/-/react-mentions-4.4.1.tgz
npm ERR! 404
npm ERR! 404  'react-mentions@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

**Comment by Sahilthakur7** [comment]
I'm also getting the same error. This needs to be fixed asap.

**Comment by noamgolani** [comment]
Had the same issue... `4.4.0` is working for me tho. 
![image](https://user-images.githubusercontent.com/10141414/170855655-509f447f-911d-42b3-acf9-770cf95e5169.png)
you can see it has 0 installs.

**Comment by Irka-sh** [comment]
Same here,  https://registry.npmjs.org/react-mentions/-/react-mentions-4.4.1.tgz does not exist

**Comment by nikgraf** [comment]
Yeah, seems like something went wrong publishing the version. There is also no readme on NPM for this version https://www.npmjs.com/package/react-mentions/v/4.4.1

**Comment by AbrahamJulian** [comment]
Having the same issue, even though I'm using version 4.0.2. Getting the same error during npm-install script pipeline.

**Comment by alexszasz** [comment]
Same issue here. i had to force 4.4.0 to get it to work

**Comment by divosuplente** [comment]
Same issue. The @pnp/spfx-controls-react library depends on this package and right now pipelines that depend on it are broken. We need this solved as soon as possible. Thanks!

**Comment by atilafassina** [comment]
Sorry, folks.
Our release job seems to be busted.

I manually released a `4.4.2`

**Comment by nikgraf** [comment]
thanks @atilafassina

btw thanks for all the great work on the lib, it works really well! 👏👏👏
