### ISSUE TITLE
4.4.2 doesn't seem to include the 4.4.0 changes

### ISSUE THREAD

**Issue by nikgraf** [signavio/react-mentions#585]
4.4.0 was supposed to include these changes to make copy & paste work with disabled inputs: https://github.com/signavio/react-mentions/pull/570/files#diff-b93f5486e33dabca047d7813cfda3b850e21823fdb3dae6ad48f6b2f7662ba8eL403-R406

**Observed behaviour:**

4.4.2 doesn't seems to include these changes in the node_modules package.
The function still gets the selection from the state:

```js
    key: "saveSelectionToClipboard",
    value: function saveSelectionToClipboard(event) {
      var _this$state4 = this.state,
          selectionStart = _this$state4.selectionStart,
          selectionEnd = _this$state4.selectionEnd;
```

@atilafassina maybe something went wrong manually releasing the package?

**Expected behaviour:**

When I do `yarn build` on my machine I get the following reuslt:

```js
    key: "saveSelectionToClipboard",
    value: function saveSelectionToClipboard(event) {
      // use the actual selectionStart & selectionEnd instead of the one stored
      // in state to ensure copy & paste also works on disabled inputs & textareas
      var selectionStart = this.inputElement.selectionStart;
      var selectionEnd = this.inputElement.selectionEnd;
```

**Comment by martindines** [comment]
To add to this issue: NPM packages for releases 4.4.0 and 4.4.2 are built from 4.3.2 and are missing the customSuggestionsContainer feature

**Comment by nikgraf** [comment]
thanks for fixing it @atilafassina 👏👏👏

**Comment by atilafassina** [comment]
I'm actually sorry it took so long.
but now the release pipeline fully refactored and is a bit more transparent, so hopefully it will be more inviting and easy to fix.
