### ISSUE TITLE
Initial position of suggestions box is incorrect

### ISSUE THREAD

**Issue by j-em** [signavio/react-mentions#626]
**Steps to reproduce:**
1. Go to https://react-mentions.vercel.app/
2. Try to @mention people in any examples

**Expected behaviour:**
The suggestions box is positioned properly

**Observed behaviour:**
Initial position of suggestions box doesn't seem correct
![2022-11-15 09 28 11](https://user-images.githubusercontent.com/943725/202204675-734abd1c-88e5-4b31-ad10-d394f5cb7ad4.gif)

**Workaround:**
Clicking outside and clicking back into the input seem to re-position the suggestions box correctly

**Comment by shivagoud** [comment]
Is this bug recently introduced or it was there all along?

**Comment by shivagoud** [comment]
@j-em use previous version, it works fine

**Comment by j-em** [comment]
@shivagoud Which version are you proposing exactly? I have the same issue with all the previous versions I tried (4.4.6, 4.3.0, 4.2.0, etc...)

**Comment by ClementCastel** [comment]
I downgraded to 4.4.6, now it works fine :)

**Comment by gabrielmicko** [comment]
Thanks for filing an issue. I have the same problem.

**Comment by lagroms** [comment]
Same issue
