### ISSUE TITLE
Is there a way to ensure that the suggestions list stays above where the user is typing?

### ISSUE THREAD

**Issue by Pau1fitz** [signavio/react-mentions#642]
Is there a way to ensure that the suggestions list stays above where the user is typing?

See below for an example of how the suggestions always stay above the first instance of @

![Kapture 2023-01-07 at 14 30 09](https://user-images.githubusercontent.com/6873736/211155772-cc788875-a0f7-4a37-aff7-cd36f10026c6.gif)

**Comment by Pau1fitz** [comment]
this was working fine in v.4.4.6

**Comment by MoidHasanBeig** [comment]
Hey @Pau1fitz, how did you achieve this after downgrading to 4.4.6??

**Comment by impzero** [comment]
How did you fix it?
