### ISSUE TITLE
how exactly to use renderSuggestions to custom the mention suggestion rendered

### ISSUE THREAD

**Issue by Ihsanasfari** [signavio/react-mentions#753]
i try the renderSuggestions like this:

![image](https://github.com/user-attachments/assets/b008f4b3-19b3-433b-aaca-14ca2f2b8d01)
![image](https://github.com/user-attachments/assets/59693bf1-f794-4e46-83b9-9957600d7b69)

i console.log the renderSuggestion but not executed, anyone can help?

**Comment by rafaelderolez** [comment]
@Ihsanasfari You should use `renderSuggestion` on `MentionInput`

`renderSuggestion` ✅
`renderSuggestions` 🔴

**Comment by Ihsanasfari** [comment]
> @Ihsanasfari You should use `renderSuggestion` on `Mention`
> 
> `renderSuggestion` ✅ `renderSuggestions` 🔴

thanks a lot!
