### ISSUE TITLE
onRemove function for Mention component?

### ISSUE THREAD

**Issue by t1mmen** [signavio/react-mentions#92]
Hi,

Have you considered adding a way to detect when a mention gets removed? 

Right now, I'm using `onAdd` to keep a list of `tagIds` for database associations, but I'd like to avoid associating tags that were added, but later removed. Ideas?

PS: Thanks again for an awesome plugin!

**Comment by kidequinox** [comment]
I noticed the onRemove method in this example, but when I try it, it does not work:
[https://github.com/effektif/react-mentions/blob/02b0da15bb2ad8f756e42ff40d25f0386f163ffe/gh-pages/views/examples/MultipleTriggerView.js](url)

**Comment by Predjo** [comment]
There is a onRemove prop on mention component but it is not used anywhere. Any chance this will be implemented?

**Comment by jfschwarz** [comment]
We would be more than happy to accept a PR for this ;)

**Comment by Tommy10802** [comment]
hello guys some news about this functionality, because i need "onRemove" function too :)

**Comment by warjohn123** [comment]
hi any news about this?

**Comment by jfschwarz** [comment]
I don't think anyone is actively working on this. It would be good extension and I'm happy to provide some help if someone wants to take this one.

(For our product at Signavio we do not need this feature, so we won't implement this anytime soon.)

**Comment by walidvb** [comment]
I'll be happy to take a lok, @jfschwarz can you point me to where you detect the backspace event? Can't seem to find where the trigger happens :/

**Comment by jfschwarz** [comment]
@walidvb I don't think the key event handler is the right place to implement this. There are more events than just backspace press that can cause a mention to be removed, e.g, text selection & `cmd+x` / type something else.

It should rather be implemented as part of the `onChange` handling, where we would have to compare the set of mentions in the new value with the set of mentions in the previous value and trigger the `onRemove` for all the mentions in the difference of these sets. 

Thinking about this, I realize this can just as well be implemented outside the core MentionsInput component. I'd suggest implementing the `onRemove` event in a wrapping component in user land that passes a proper `onChange` handler to MentionsInput. Of course it would be great if you could share your implementation here.

**Comment by walidvb** [comment]
I hear you about the wrapper, although I believe this should be part of tool(considering you can detect addition already).
I've worked around it and now process that information server-side, but I will likely need something front-end, and will share whatever solution I came up with, if and when I do.

Thanks!

**Comment by NarasimhaReddyY** [comment]
@jfschwarz 

Do you have any workaround for this?

**Comment by frontendphil** [comment]
@NarasimhaReddyY described a workaround already here: https://github.com/signavio/react-mentions/issues/92#issuecomment-355821945 Do you have any further questions?

**Comment by NarasimhaReddyY** [comment]
@frontendphil  Got it. Thanks.

**Comment by jrkt** [comment]
Can someone share their code implementation of this workaround?

**Comment by metroid09** [comment]
I've been working on a PR for this. https://github.com/signavio/react-mentions/pull/288

**Comment by zenVentzi** [comment]
What's up with the PR? I agree that onAdd only makes sense if there is onRemove. Without onRemove, we're making the assumption that user never removes any mentions, which is unlikely.

**Comment by jfschwarz** [comment]
We are not planning to add this feature. See https://github.com/signavio/react-mentions/pull/288#issuecomment-496870103 for our reasoning.

**Comment by busraguler** [comment]
https://codesandbox.io/s/08t27?file=/src/index.js:2341-2372

**Comment by abhishek-ts-goodgist** [comment]
You can follow below approach to find a solution when you remove or add any item , to always get the updated array from the  library. Kindly check the below screenshots
![image](https://github.com/signavio/react-mentions/assets/150001622/a6dae2f5-4a96-46e0-89ae-f44ec90ddd0f)
Then later these functions has to be passed this way ,
`<MentionsInput
        value={mentionedText}
        onChange={onChange}
        placeholder={
          placeholder }
        allowSuggestionsAboveCursor={true}
        style={defaultStyle(themeContext.currentTheme)}
        className="w-75"
        onKeyDown={(event) => {
          if (event.key === "Enter") {
            if (onSubmit) {
              const plainText = stripMentions(mentionedText);
              onSubmit(mentionedData, plainText);
            }
            if (callback) callback(mentionedData);
          }
        }}
        singleLine
        disabled={disabled ?? false}
      >
        <Mention
          appendSpaceOnAdd
          trigger="@"
          data={data}
          style={defaultMentionStyle(themeContext.currentTheme)}
          onAdd={(id, display) =>
            {
              handleAdd(
                id,
                display,
                data.find((item) => item.id === id)
              )
            }
          }
          renderSuggestion={renderSuggestion}
        />
      </MentionsInput>`
